/**
 * Afghanistan netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Afghanistan
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: AF-2019.343.671
 */
2001:df0:d500::/48 Deny No access allowed from Afghanistan
2001:df5:f300::/48 Deny No access allowed from Afghanistan
2400:1980::/32 Deny No access allowed from Afghanistan
2400:3080::/32 Deny No access allowed from Afghanistan
2400:5180::/32 Deny No access allowed from Afghanistan
2400:9cc0::/32 Deny No access allowed from Afghanistan
2400:bdc0::/32 Deny No access allowed from Afghanistan
2400:d5c0::/32 Deny No access allowed from Afghanistan
2400:e500::/32 Deny No access allowed from Afghanistan
2400:e640::/32 Deny No access allowed from Afghanistan
2401:8080::/32 Deny No access allowed from Afghanistan
2402:2880::/32 Deny No access allowed from Afghanistan
2402:3440::/32 Deny No access allowed from Afghanistan
2402:4e40::/32 Deny No access allowed from Afghanistan
2402:dd80::/32 Deny No access allowed from Afghanistan
2402:e080::/32 Deny No access allowed from Afghanistan
2403:3e40::/32 Deny No access allowed from Afghanistan
2403:f140::/32 Deny No access allowed from Afghanistan
2404:6240::/32 Deny No access allowed from Afghanistan
2404:9b00::/32 Deny No access allowed from Afghanistan
2404:9f40::/32 Deny No access allowed from Afghanistan
2405:2240::/32 Deny No access allowed from Afghanistan
2406:5700::/32 Deny No access allowed from Afghanistan
2406:a100::/32 Deny No access allowed from Afghanistan
2406:d100::/32 Deny No access allowed from Afghanistan
Origin: AF
