/**
 * Afghanistan netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Afghanistan
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: AF-2019.343.671
 */
5.62.61.236/30 Deny No access allowed from Afghanistan
5.62.63.232/30 Deny No access allowed from Afghanistan
27.116.56.0/22 Deny No access allowed from Afghanistan
43.230.209.0/24 Deny No access allowed from Afghanistan
43.231.131.0/24 Deny No access allowed from Afghanistan
43.249.40.0/22 Deny No access allowed from Afghanistan
43.250.136.0/22 Deny No access allowed from Afghanistan
45.12.70.3/32 Deny No access allowed from Afghanistan
45.12.71.3/32 Deny No access allowed from Afghanistan
45.65.58.0/23 Deny No access allowed from Afghanistan
45.116.128.0/23 Deny No access allowed from Afghanistan
45.125.224.0/22 Deny No access allowed from Afghanistan
45.126.253.0/24 Deny No access allowed from Afghanistan
46.36.202.201/32 Deny No access allowed from Afghanistan
46.36.202.202/31 Deny No access allowed from Afghanistan
46.36.202.204/31 Deny No access allowed from Afghanistan
58.147.128.0/19 Deny No access allowed from Afghanistan
59.153.124.0/22 Deny No access allowed from Afghanistan
61.5.192.0/20 Deny No access allowed from Afghanistan
64.207.208.0/21 Deny No access allowed from Afghanistan
74.118.80.0/22 Deny No access allowed from Afghanistan
77.234.45.180/32 Deny No access allowed from Afghanistan
80.78.23.96/29 Deny No access allowed from Afghanistan
91.109.216.0/21 Deny No access allowed from Afghanistan
103.5.172.0/22 Deny No access allowed from Afghanistan
103.5.196.0/23 Deny No access allowed from Afghanistan
103.7.104.0/22 Deny No access allowed from Afghanistan
103.12.96.0/22 Deny No access allowed from Afghanistan
103.13.64.0/22 Deny No access allowed from Afghanistan
103.15.238.0/23 Deny No access allowed from Afghanistan
103.17.60.0/22 Deny No access allowed from Afghanistan
103.17.165.0/24 Deny No access allowed from Afghanistan
103.17.166.0/23 Deny No access allowed from Afghanistan
103.18.160.0/22 Deny No access allowed from Afghanistan
103.23.36.0/22 Deny No access allowed from Afghanistan
103.28.132.0/22 Deny No access allowed from Afghanistan
103.30.136.0/22 Deny No access allowed from Afghanistan
103.35.166.0/23 Deny No access allowed from Afghanistan
103.41.8.0/23 Deny No access allowed from Afghanistan
103.42.0.0/22 Deny No access allowed from Afghanistan
103.46.208.0/22 Deny No access allowed from Afghanistan
103.53.16.0/22 Deny No access allowed from Afghanistan
103.53.24.0/22 Deny No access allowed from Afghanistan
103.71.59.0/24 Deny No access allowed from Afghanistan
103.83.18.0/23 Deny No access allowed from Afghanistan
103.84.97.0/24 Deny No access allowed from Afghanistan
103.86.124.0/22 Deny No access allowed from Afghanistan
103.87.88.0/24 Deny No access allowed from Afghanistan
103.88.192.0/22 Deny No access allowed from Afghanistan
103.89.152.0/23 Deny No access allowed from Afghanistan
103.93.92.0/24 Deny No access allowed from Afghanistan
103.93.254.0/24 Deny No access allowed from Afghanistan
103.94.24.0/23 Deny No access allowed from Afghanistan
103.96.233.0/24 Deny No access allowed from Afghanistan
103.102.220.0/23 Deny No access allowed from Afghanistan
103.104.146.0/23 Deny No access allowed from Afghanistan
103.106.182.0/24 Deny No access allowed from Afghanistan
103.110.53.0/24 Deny No access allowed from Afghanistan
103.110.54.0/23 Deny No access allowed from Afghanistan
103.112.177.0/24 Deny No access allowed from Afghanistan
103.112.178.0/23 Deny No access allowed from Afghanistan
103.114.128.0/23 Deny No access allowed from Afghanistan
103.115.14.0/23 Deny No access allowed from Afghanistan
103.116.25.0/24 Deny No access allowed from Afghanistan
103.119.24.0/22 Deny No access allowed from Afghanistan
103.119.236.0/23 Deny No access allowed from Afghanistan
103.125.100.0/22 Deny No access allowed from Afghanistan
103.125.186.0/24 Deny No access allowed from Afghanistan
103.126.4.0/23 Deny No access allowed from Afghanistan
103.127.116.0/22 Deny No access allowed from Afghanistan
103.132.98.0/23 Deny No access allowed from Afghanistan
103.133.75.0/24 Deny No access allowed from Afghanistan
103.133.82.0/23 Deny No access allowed from Afghanistan
103.142.212.0/23 Deny No access allowed from Afghanistan
103.143.204.0/23 Deny No access allowed from Afghanistan
103.144.237.0/24 Deny No access allowed from Afghanistan
103.145.166.0/24 Deny No access allowed from Afghanistan
103.213.104.0/22 Deny No access allowed from Afghanistan
103.215.210.0/23 Deny No access allowed from Afghanistan
103.216.160.0/24 Deny No access allowed from Afghanistan
103.224.127.0/24 Deny No access allowed from Afghanistan
103.224.214.0/23 Deny No access allowed from Afghanistan
103.227.16.0/22 Deny No access allowed from Afghanistan
103.230.252.0/22 Deny No access allowed from Afghanistan
103.233.183.0/24 Deny No access allowed from Afghanistan
103.235.176.0/22 Deny No access allowed from Afghanistan
103.237.83.0/24 Deny No access allowed from Afghanistan
103.241.156.0/22 Deny No access allowed from Afghanistan
103.242.50.0/23 Deny No access allowed from Afghanistan
103.243.179.0/24 Deny No access allowed from Afghanistan
103.244.144.0/22 Deny No access allowed from Afghanistan
103.247.198.0/24 Deny No access allowed from Afghanistan
103.251.176.0/22 Deny No access allowed from Afghanistan
103.254.166.0/24 Deny No access allowed from Afghanistan
109.235.203.0/28 Deny No access allowed from Afghanistan
109.235.203.176/29 Deny No access allowed from Afghanistan
111.125.152.0/21 Deny No access allowed from Afghanistan
116.204.160.0/22 Deny No access allowed from Afghanistan
116.204.240.0/22 Deny No access allowed from Afghanistan
117.55.192.0/20 Deny No access allowed from Afghanistan
117.104.224.0/21 Deny No access allowed from Afghanistan
119.59.80.0/21 Deny No access allowed from Afghanistan
121.100.48.0/21 Deny No access allowed from Afghanistan
121.127.32.0/19 Deny No access allowed from Afghanistan
122.201.44.48/28 Deny No access allowed from Afghanistan
125.213.192.0/19 Deny No access allowed from Afghanistan
125.253.152.0/22 Deny No access allowed from Afghanistan
125.253.156.0/23 Deny No access allowed from Afghanistan
128.41.128.0/17 Deny No access allowed from Afghanistan
137.59.120.0/22 Deny No access allowed from Afghanistan
149.54.0.0/17 Deny No access allowed from Afghanistan
154.59.40.0/24 Deny No access allowed from Afghanistan
154.59.42.0/23 Deny No access allowed from Afghanistan
154.59.44.0/22 Deny No access allowed from Afghanistan
155.254.225.0/24 Deny No access allowed from Afghanistan
158.175.72.32/28 Deny No access allowed from Afghanistan
158.175.72.160/27 Deny No access allowed from Afghanistan
158.176.125.128/28 Deny No access allowed from Afghanistan
163.47.160.0/22 Deny No access allowed from Afghanistan
169.46.204.240/28 Deny No access allowed from Afghanistan
169.48.66.224/28 Deny No access allowed from Afghanistan
169.48.113.32/27 Deny No access allowed from Afghanistan
169.55.59.80/28 Deny No access allowed from Afghanistan
169.55.60.244/32 Deny No access allowed from Afghanistan
169.55.177.112/28 Deny No access allowed from Afghanistan
169.60.71.192/28 Deny No access allowed from Afghanistan
172.111.208.0/24 Deny No access allowed from Afghanistan
175.106.32.0/19 Deny No access allowed from Afghanistan
180.94.64.0/19 Deny No access allowed from Afghanistan
180.222.136.0/21 Deny No access allowed from Afghanistan
185.27.248.0/24 Deny No access allowed from Afghanistan
185.27.250.0/24 Deny No access allowed from Afghanistan
185.178.144.0/22 Deny No access allowed from Afghanistan
185.193.212.0/22 Deny No access allowed from Afghanistan
194.50.99.3/32 Deny No access allowed from Afghanistan
194.50.111.3/32 Deny No access allowed from Afghanistan
194.98.43.0/24 Deny No access allowed from Afghanistan
196.195.0.0/20 Deny No access allowed from Afghanistan
196.195.240.0/20 Deny No access allowed from Afghanistan
198.27.95.228/30 Deny No access allowed from Afghanistan
198.46.141.128/29 Deny No access allowed from Afghanistan
199.168.188.32/29 Deny No access allowed from Afghanistan
202.3.76.0/24 Deny No access allowed from Afghanistan
202.56.176.0/20 Deny No access allowed from Afghanistan
202.86.16.0/20 Deny No access allowed from Afghanistan
203.174.27.0/24 Deny No access allowed from Afghanistan
203.215.32.0/20 Deny No access allowed from Afghanistan
206.123.150.0/25 Deny No access allowed from Afghanistan
210.5.214.128/29 Deny No access allowed from Afghanistan
223.26.20.0/22 Deny No access allowed from Afghanistan
Origin: AF
