/**
 * Armenia netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Armenia
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: AM-2019.343.671
 */
2001:67c:21c::/48 Deny No access allowed from Armenia
2001:67c:2cdc::/48 Deny No access allowed from Armenia
2001:7f8:94::/48 Deny No access allowed from Armenia
2001:7f9:8::/48 Deny No access allowed from Armenia
2001:4d00::/32 Deny No access allowed from Armenia
2001:4d78:fe05:90:1::/80 Deny No access allowed from Armenia
2400:cb00:117::/48 Deny No access allowed from Armenia
2620:0:876:7900::/56 Deny No access allowed from Armenia
2a00:f38::/32 Deny No access allowed from Armenia
2a00:1500::/29 Deny No access allowed from Armenia
2a00:1f28::/32 Deny No access allowed from Armenia
2a00:cc40::/29 Deny No access allowed from Armenia
2a01:4000::/32 Deny No access allowed from Armenia
2a01:4a00::/32 Deny No access allowed from Armenia
2a01:bbc0::/32 Deny No access allowed from Armenia
2a02:29f8::/32 Deny No access allowed from Armenia
2a02:2a50::/29 Deny No access allowed from Armenia
2a02:5960::/32 Deny No access allowed from Armenia
2a03:1080::/32 Deny No access allowed from Armenia
2a03:1900::/29 Deny No access allowed from Armenia
2a03:2300::/29 Deny No access allowed from Armenia
2a03:27c0::/32 Deny No access allowed from Armenia
2a03:3d00::/32 Deny No access allowed from Armenia
2a03:5620::/32 Deny No access allowed from Armenia
2a03:6947:200::/40 Deny No access allowed from Armenia
2a05:f140::/29 Deny No access allowed from Armenia
2a06:33c0::/29 Deny No access allowed from Armenia
2a07:66c0::/29 Deny No access allowed from Armenia
2a09:6c80::/32 Deny No access allowed from Armenia
2a09:f840::/29 Deny No access allowed from Armenia
2a0a:9c0::/29 Deny No access allowed from Armenia
2a0a:3440::/29 Deny No access allowed from Armenia
2a0a:3880::/29 Deny No access allowed from Armenia
2a0b:a3c0::/29 Deny No access allowed from Armenia
2a0b:ff80::/29 Deny No access allowed from Armenia
2a0c:6dc0::/29 Deny No access allowed from Armenia
2a0d:b800::/29 Deny No access allowed from Armenia
2a0e:2d80::/29 Deny No access allowed from Armenia
2a0e:6040::/29 Deny No access allowed from Armenia
2a0e:7100::/29 Deny No access allowed from Armenia
Origin: AM
