/**
 * Armenia netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Armenia
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: AM-2019.343.671
 */
2.56.204.0/22 Deny No access allowed from Armenia
5.39.204.0/22 Deny No access allowed from Armenia
5.62.60.12/30 Deny No access allowed from Armenia
5.62.62.12/30 Deny No access allowed from Armenia
5.63.160.0/21 Deny No access allowed from Armenia
5.77.128.0/17 Deny No access allowed from Armenia
5.101.222.0/25 Deny No access allowed from Armenia
5.134.80.0/21 Deny No access allowed from Armenia
31.7.160.0/21 Deny No access allowed from Armenia
31.47.192.0/21 Deny No access allowed from Armenia
31.132.76.0/24 Deny No access allowed from Armenia
37.26.168.0/21 Deny No access allowed from Armenia
37.157.208.0/20 Deny No access allowed from Armenia
37.186.64.0/18 Deny No access allowed from Armenia
37.252.64.0/19 Deny No access allowed from Armenia
37.252.216.0/22 Deny No access allowed from Armenia
45.11.136.0/22 Deny No access allowed from Armenia
45.12.70.7/32 Deny No access allowed from Armenia
45.12.71.7/32 Deny No access allowed from Armenia
45.15.148.0/22 Deny No access allowed from Armenia
45.59.129.0/24 Deny No access allowed from Armenia
45.131.124.0/22 Deny No access allowed from Armenia
45.133.104.0/22 Deny No access allowed from Armenia
45.143.104.0/22 Deny No access allowed from Armenia
45.143.204.0/22 Deny No access allowed from Armenia
45.153.212.0/22 Deny No access allowed from Armenia
45.159.72.0/22 Deny No access allowed from Armenia
46.19.96.0/21 Deny No access allowed from Armenia
46.36.112.0/20 Deny No access allowed from Armenia
46.70.0.0/15 Deny No access allowed from Armenia
46.130.0.0/16 Deny No access allowed from Armenia
46.162.192.0/18 Deny No access allowed from Armenia
46.182.168.0/21 Deny No access allowed from Armenia
46.241.128.0/17 Deny No access allowed from Armenia
57.88.0.0/20 Deny No access allowed from Armenia
62.89.0.0/19 Deny No access allowed from Armenia
66.102.33.192/26 Deny No access allowed from Armenia
69.28.56.0/32 Deny No access allowed from Armenia
77.95.184.0/21 Deny No access allowed from Armenia
78.109.64.0/20 Deny No access allowed from Armenia
79.170.200.0/21 Deny No access allowed from Armenia
80.86.224.0/20 Deny No access allowed from Armenia
81.16.0.0/20 Deny No access allowed from Armenia
81.89.208.0/20 Deny No access allowed from Armenia
82.199.192.0/20 Deny No access allowed from Armenia
83.139.0.0/18 Deny No access allowed from Armenia
85.203.22.48/28 Deny No access allowed from Armenia
87.241.128.0/18 Deny No access allowed from Armenia
88.84.157.204/30 Deny No access allowed from Armenia
89.249.192.0/20 Deny No access allowed from Armenia
91.103.24.0/21 Deny No access allowed from Armenia
91.103.56.0/21 Deny No access allowed from Armenia
91.103.248.0/22 Deny No access allowed from Armenia
91.195.254.0/23 Deny No access allowed from Armenia
91.196.36.0/22 Deny No access allowed from Armenia
91.198.108.0/23 Deny No access allowed from Armenia
91.199.38.0/24 Deny No access allowed from Armenia
91.199.226.0/24 Deny No access allowed from Armenia
91.204.188.0/22 Deny No access allowed from Armenia
91.205.132.0/22 Deny No access allowed from Armenia
91.205.136.0/21 Deny No access allowed from Armenia
91.205.196.0/22 Deny No access allowed from Armenia
91.208.76.0/24 Deny No access allowed from Armenia
91.209.38.0/24 Deny No access allowed from Armenia
91.210.40.0/22 Deny No access allowed from Armenia
91.212.71.0/24 Deny No access allowed from Armenia
91.217.157.0/24 Deny No access allowed from Armenia
91.218.4.0/22 Deny No access allowed from Armenia
91.218.180.0/22 Deny No access allowed from Armenia
91.220.126.0/24 Deny No access allowed from Armenia
91.221.228.0/23 Deny No access allowed from Armenia
91.226.235.0/24 Deny No access allowed from Armenia
91.231.200.0/22 Deny No access allowed from Armenia
92.43.136.0/21 Deny No access allowed from Armenia
93.94.216.0/21 Deny No access allowed from Armenia
93.170.9.0/24 Deny No access allowed from Armenia
93.185.32.0/20 Deny No access allowed from Armenia
93.187.160.0/21 Deny No access allowed from Armenia
94.228.24.0/21 Deny No access allowed from Armenia
95.140.192.0/20 Deny No access allowed from Armenia
104.243.249.0/24 Deny No access allowed from Armenia
109.68.120.0/21 Deny No access allowed from Armenia
109.75.32.0/20 Deny No access allowed from Armenia
109.105.159.0/24 Deny No access allowed from Armenia
130.193.120.0/21 Deny No access allowed from Armenia
141.136.64.0/19 Deny No access allowed from Armenia
157.167.75.0/24 Deny No access allowed from Armenia
158.46.182.0/23 Deny No access allowed from Armenia
163.172.140.230/32 Deny No access allowed from Armenia
172.68.124.0/22 Deny No access allowed from Armenia
172.94.35.0/24 Deny No access allowed from Armenia
176.32.192.0/21 Deny No access allowed from Armenia
176.113.118.0/24 Deny No access allowed from Armenia
176.124.96.0/21 Deny No access allowed from Armenia
178.72.128.0/18 Deny No access allowed from Armenia
178.78.128.0/18 Deny No access allowed from Armenia
178.160.128.0/17 Deny No access allowed from Armenia
178.213.128.0/21 Deny No access allowed from Armenia
178.219.48.0/20 Deny No access allowed from Armenia
181.215.133.80/28 Deny No access allowed from Armenia
185.3.188.0/24 Deny No access allowed from Armenia
185.8.0.0/22 Deny No access allowed from Armenia
185.13.196.0/22 Deny No access allowed from Armenia
185.18.72.0/22 Deny No access allowed from Armenia
185.21.252.0/22 Deny No access allowed from Armenia
185.36.36.0/22 Deny No access allowed from Armenia
185.44.228.0/22 Deny No access allowed from Armenia
185.48.240.0/22 Deny No access allowed from Armenia
185.57.68.0/22 Deny No access allowed from Armenia
185.59.68.0/22 Deny No access allowed from Armenia
185.77.192.0/22 Deny No access allowed from Armenia
185.78.144.0/22 Deny No access allowed from Armenia
185.79.0.0/22 Deny No access allowed from Armenia
185.86.192.0/22 Deny No access allowed from Armenia
185.92.84.0/22 Deny No access allowed from Armenia
185.121.236.0/22 Deny No access allowed from Armenia
185.127.64.0/22 Deny No access allowed from Armenia
185.149.140.0/22 Deny No access allowed from Armenia
185.150.164.0/22 Deny No access allowed from Armenia
185.155.233.138/32 Deny No access allowed from Armenia
185.177.104.0/22 Deny No access allowed from Armenia
185.182.120.0/22 Deny No access allowed from Armenia
185.193.12.0/22 Deny No access allowed from Armenia
185.208.153.0/24 Deny No access allowed from Armenia
185.215.52.0/22 Deny No access allowed from Armenia
185.223.124.0/22 Deny No access allowed from Armenia
185.247.0.0/22 Deny No access allowed from Armenia
188.115.192.0/18 Deny No access allowed from Armenia
188.164.152.0/21 Deny No access allowed from Armenia
193.57.28.0/22 Deny No access allowed from Armenia
193.142.19.0/24 Deny No access allowed from Armenia
194.30.176.0/23 Deny No access allowed from Armenia
194.31.4.0/23 Deny No access allowed from Armenia
194.39.82.0/23 Deny No access allowed from Armenia
194.39.102.0/23 Deny No access allowed from Armenia
194.50.99.7/32 Deny No access allowed from Armenia
194.61.88.0/22 Deny No access allowed from Armenia
194.247.50.0/24 Deny No access allowed from Armenia
195.8.50.0/23 Deny No access allowed from Armenia
195.43.74.0/23 Deny No access allowed from Armenia
195.60.80.128/27 Deny No access allowed from Armenia
195.88.66.0/23 Deny No access allowed from Armenia
195.88.254.0/23 Deny No access allowed from Armenia
195.128.166.0/23 Deny No access allowed from Armenia
195.191.100.0/23 Deny No access allowed from Armenia
195.191.154.0/23 Deny No access allowed from Armenia
195.191.186.0/23 Deny No access allowed from Armenia
195.225.234.0/23 Deny No access allowed from Armenia
195.250.64.0/19 Deny No access allowed from Armenia
198.50.101.0/29 Deny No access allowed from Armenia
212.34.224.0/19 Deny No access allowed from Armenia
212.42.192.0/19 Deny No access allowed from Armenia
212.73.64.0/19 Deny No access allowed from Armenia
213.208.38.0/24 Deny No access allowed from Armenia
217.76.0.0/20 Deny No access allowed from Armenia
217.113.0.0/19 Deny No access allowed from Armenia
Origin: AM
