/**
 * Bahrain netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Bahrain
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: BH-2019.343.671
 */
2001:500:15:5900::/56 Deny No access allowed from Bahrain
2001:7f8:4f::/48 Deny No access allowed from Bahrain
2001:1a40::/32 Deny No access allowed from Bahrain
2400:cb00:170::/48 Deny No access allowed from Bahrain
2600:1f01:48e0::/47 Deny No access allowed from Bahrain
2a00:1150::/32 Deny No access allowed from Bahrain
2a00:6600::/32 Deny No access allowed from Bahrain
2a00:dde0::/32 Deny No access allowed from Bahrain
2a01:3e0:3c00::/60 Deny No access allowed from Bahrain
2a01:4600::/32 Deny No access allowed from Bahrain
2a01:4900::/32 Deny No access allowed from Bahrain
2a01:5d80::/32 Deny No access allowed from Bahrain
2a02:2578::/32 Deny No access allowed from Bahrain
2a02:c3c0::/29 Deny No access allowed from Bahrain
2a02:c400::/29 Deny No access allowed from Bahrain
2a02:d080::/29 Deny No access allowed from Bahrain
2a03:1c00::/32 Deny No access allowed from Bahrain
2a04:8ac0::/29 Deny No access allowed from Bahrain
2a05:d000:e000::/40 Deny No access allowed from Bahrain
2a05:d01e::/36 Deny No access allowed from Bahrain
2a05:d050:e000::/40 Deny No access allowed from Bahrain
2a05:d078:e000::/40 Deny No access allowed from Bahrain
2a05:d079:e000::/40 Deny No access allowed from Bahrain
2a05:d07a:e000::/40 Deny No access allowed from Bahrain
2a05:d07c:e000::/40 Deny No access allowed from Bahrain
2a05:d07e:e000::/40 Deny No access allowed from Bahrain
2a05:d07f:e000::/40 Deny No access allowed from Bahrain
2a0e:6700::/32 Deny No access allowed from Bahrain
2a0e:6703::/32 Deny No access allowed from Bahrain
2a0e:6704::/30 Deny No access allowed from Bahrain
Origin: BH
