/**
 * Bahrain netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Bahrain
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: BH-2019.343.671
 */
5.1.42.0/24 Deny No access allowed from Bahrain
5.62.60.20/30 Deny No access allowed from Bahrain
5.62.62.20/30 Deny No access allowed from Bahrain
13.248.106.0/24 Deny No access allowed from Bahrain
15.185.0.0/16 Deny No access allowed from Bahrain
23.247.137.0/24 Deny No access allowed from Bahrain
37.131.0.0/17 Deny No access allowed from Bahrain
45.11.72.0/24 Deny No access allowed from Bahrain
45.11.75.0/24 Deny No access allowed from Bahrain
45.12.70.23/32 Deny No access allowed from Bahrain
45.12.71.23/32 Deny No access allowed from Bahrain
45.149.84.0/22 Deny No access allowed from Bahrain
46.42.64.0/18 Deny No access allowed from Bahrain
46.184.128.0/17 Deny No access allowed from Bahrain
46.235.208.0/21 Deny No access allowed from Bahrain
46.243.150.0/24 Deny No access allowed from Bahrain
52.93.69.0/24 Deny No access allowed from Bahrain
52.93.224.0/22 Deny No access allowed from Bahrain
52.94.249.160/28 Deny No access allowed from Bahrain
52.95.172.0/23 Deny No access allowed from Bahrain
52.95.174.0/24 Deny No access allowed from Bahrain
52.95.228.0/24 Deny No access allowed from Bahrain
52.119.249.0/24 Deny No access allowed from Bahrain
54.239.1.112/28 Deny No access allowed from Bahrain
57.88.32.0/20 Deny No access allowed from Bahrain
57.98.96.0/20 Deny No access allowed from Bahrain
62.209.0.0/19 Deny No access allowed from Bahrain
66.96.112.192/26 Deny No access allowed from Bahrain
74.80.90.0/24 Deny No access allowed from Bahrain
77.69.128.0/17 Deny No access allowed from Bahrain
77.83.88.0/22 Deny No access allowed from Bahrain
77.92.160.0/19 Deny No access allowed from Bahrain
78.110.64.0/20 Deny No access allowed from Bahrain
79.171.240.0/21 Deny No access allowed from Bahrain
80.88.240.0/20 Deny No access allowed from Bahrain
80.95.208.0/20 Deny No access allowed from Bahrain
80.241.144.0/20 Deny No access allowed from Bahrain
81.22.16.0/20 Deny No access allowed from Bahrain
82.194.32.0/19 Deny No access allowed from Bahrain
82.195.187.18/32 Deny No access allowed from Bahrain
83.136.56.0/21 Deny No access allowed from Bahrain
84.255.128.0/18 Deny No access allowed from Bahrain
85.158.128.0/21 Deny No access allowed from Bahrain
87.236.48.0/21 Deny No access allowed from Bahrain
87.236.136.0/21 Deny No access allowed from Bahrain
87.237.192.0/21 Deny No access allowed from Bahrain
87.252.96.0/22 Deny No access allowed from Bahrain
87.252.100.0/24 Deny No access allowed from Bahrain
87.252.102.0/23 Deny No access allowed from Bahrain
87.252.104.0/23 Deny No access allowed from Bahrain
87.252.126.0/23 Deny No access allowed from Bahrain
88.201.0.0/17 Deny No access allowed from Bahrain
89.31.192.0/21 Deny No access allowed from Bahrain
89.148.0.0/18 Deny No access allowed from Bahrain
91.189.188.0/22 Deny No access allowed from Bahrain
93.95.24.0/21 Deny No access allowed from Bahrain
93.188.192.0/21 Deny No access allowed from Bahrain
94.76.0.0/18 Deny No access allowed from Bahrain
94.79.192.0/18 Deny No access allowed from Bahrain
95.84.64.0/18 Deny No access allowed from Bahrain
99.77.147.0/24 Deny No access allowed from Bahrain
99.78.220.0/22 Deny No access allowed from Bahrain
99.82.128.0/20 Deny No access allowed from Bahrain
99.82.144.0/21 Deny No access allowed from Bahrain
99.82.152.0/22 Deny No access allowed from Bahrain
104.166.116.0/24 Deny No access allowed from Bahrain
107.152.186.56/29 Deny No access allowed from Bahrain
109.63.0.0/17 Deny No access allowed from Bahrain
109.161.128.0/17 Deny No access allowed from Bahrain
128.90.63.0/24 Deny No access allowed from Bahrain
150.222.7.0/24 Deny No access allowed from Bahrain
155.254.215.0/24 Deny No access allowed from Bahrain
157.167.78.0/24 Deny No access allowed from Bahrain
157.175.0.0/16 Deny No access allowed from Bahrain
172.69.228.0/22 Deny No access allowed from Bahrain
176.118.176.0/22 Deny No access allowed from Bahrain
176.241.176.0/21 Deny No access allowed from Bahrain
178.132.32.0/20 Deny No access allowed from Bahrain
185.7.8.0/22 Deny No access allowed from Bahrain
185.33.176.0/22 Deny No access allowed from Bahrain
185.34.228.0/23 Deny No access allowed from Bahrain
185.34.230.0/25 Deny No access allowed from Bahrain
185.34.230.128/26 Deny No access allowed from Bahrain
185.34.230.192/29 Deny No access allowed from Bahrain
185.34.230.200/30 Deny No access allowed from Bahrain
185.34.230.204/31 Deny No access allowed from Bahrain
185.34.230.207/32 Deny No access allowed from Bahrain
185.34.230.208/28 Deny No access allowed from Bahrain
185.34.230.224/31 Deny No access allowed from Bahrain
185.34.230.226/32 Deny No access allowed from Bahrain
185.34.230.228/32 Deny No access allowed from Bahrain
185.34.230.230/31 Deny No access allowed from Bahrain
185.34.230.232/29 Deny No access allowed from Bahrain
185.34.230.240/30 Deny No access allowed from Bahrain
185.34.230.245/32 Deny No access allowed from Bahrain
185.34.230.246/31 Deny No access allowed from Bahrain
185.34.230.248/29 Deny No access allowed from Bahrain
185.34.231.0/24 Deny No access allowed from Bahrain
185.36.88.0/22 Deny No access allowed from Bahrain
185.49.160.0/22 Deny No access allowed from Bahrain
185.143.124.0/22 Deny No access allowed from Bahrain
185.156.236.0/22 Deny No access allowed from Bahrain
185.165.176.0/22 Deny No access allowed from Bahrain
185.170.12.0/22 Deny No access allowed from Bahrain
185.236.132.0/22 Deny No access allowed from Bahrain
188.116.192.0/19 Deny No access allowed from Bahrain
188.116.224.0/23 Deny No access allowed from Bahrain
188.116.226.0/24 Deny No access allowed from Bahrain
188.116.227.0/28 Deny No access allowed from Bahrain
188.116.227.16/29 Deny No access allowed from Bahrain
188.116.227.24/30 Deny No access allowed from Bahrain
188.116.227.28/31 Deny No access allowed from Bahrain
188.116.227.31/32 Deny No access allowed from Bahrain
188.116.227.32/27 Deny No access allowed from Bahrain
188.116.227.64/26 Deny No access allowed from Bahrain
188.116.227.128/25 Deny No access allowed from Bahrain
188.116.228.0/22 Deny No access allowed from Bahrain
188.116.232.0/21 Deny No access allowed from Bahrain
188.116.240.0/20 Deny No access allowed from Bahrain
188.137.128.0/17 Deny No access allowed from Bahrain
193.188.12.0/23 Deny No access allowed from Bahrain
193.188.96.0/19 Deny No access allowed from Bahrain
194.50.99.23/32 Deny No access allowed from Bahrain
194.50.111.23/32 Deny No access allowed from Bahrain
194.117.122.63/32 Deny No access allowed from Bahrain
195.82.138.0/23 Deny No access allowed from Bahrain
195.112.160.252/30 Deny No access allowed from Bahrain
195.219.152.0/24 Deny No access allowed from Bahrain
198.50.97.208/29 Deny No access allowed from Bahrain
206.159.148.137/32 Deny No access allowed from Bahrain
212.63.170.212/30 Deny No access allowed from Bahrain
212.63.176.56/32 Deny No access allowed from Bahrain
217.17.224.0/19 Deny No access allowed from Bahrain
Origin: BH
