/**
 * Belarus netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Belarus
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: BY-2019.343.671
 */
2001:67c:18a8::/48 Deny No access allowed from Belarus
2001:7f8:5a::/48 Deny No access allowed from Belarus
2001:7f8:8b::/48 Deny No access allowed from Belarus
2a00:1760::/29 Deny No access allowed from Belarus
2a00:6440::/32 Deny No access allowed from Belarus
2a00:c820::/29 Deny No access allowed from Belarus
2a01:6e40::/32 Deny No access allowed from Belarus
2a02:6bf:fff0:800::/60 Deny No access allowed from Belarus
2a02:bf0::/32 Deny No access allowed from Belarus
2a02:2208::/29 Deny No access allowed from Belarus
2a02:d240::/29 Deny No access allowed from Belarus
2a02:e300::/29 Deny No access allowed from Belarus
2a03:3000::/29 Deny No access allowed from Belarus
2a03:5be0::/32 Deny No access allowed from Belarus
2a03:9120::/32 Deny No access allowed from Belarus
2a03:9b60::/32 Deny No access allowed from Belarus
2a03:b600:365::/98 Deny No access allowed from Belarus
2a03:b600:366::/98 Deny No access allowed from Belarus
2a03:b600:367::/98 Deny No access allowed from Belarus
2a03:b600:368::/98 Deny No access allowed from Belarus
2a03:b600:369::/98 Deny No access allowed from Belarus
2a03:c740::/32 Deny No access allowed from Belarus
2a04:2e80::/29 Deny No access allowed from Belarus
2a04:9b40::/29 Deny No access allowed from Belarus
2a04:cc40::/29 Deny No access allowed from Belarus
2a05:dfc7:40::/48 Deny No access allowed from Belarus
2a06:1281:10::/44 Deny No access allowed from Belarus
2a06:1281:20::/43 Deny No access allowed from Belarus
2a06:1281:40::/42 Deny No access allowed from Belarus
2a06:1281:80::/41 Deny No access allowed from Belarus
2a06:1281:100::/40 Deny No access allowed from Belarus
2a06:1281:200::/39 Deny No access allowed from Belarus
2a06:1281:400::/38 Deny No access allowed from Belarus
2a06:1281:800::/37 Deny No access allowed from Belarus
2a06:1281:1000::/36 Deny No access allowed from Belarus
2a06:1281:2000::/35 Deny No access allowed from Belarus
2a06:1281:4000::/34 Deny No access allowed from Belarus
2a06:1281:8000::/33 Deny No access allowed from Belarus
2a06:1283::/32 Deny No access allowed from Belarus
2a06:1284::/31 Deny No access allowed from Belarus
2a06:1286::/32 Deny No access allowed from Belarus
2a06:4800::/29 Deny No access allowed from Belarus
2a07:200::/29 Deny No access allowed from Belarus
2a09:e1c1:eff0::/44 Deny No access allowed from Belarus
2a0a:7d80::/29 Deny No access allowed from Belarus
2a0a:eac0::/29 Deny No access allowed from Belarus
2a0a:f240::/29 Deny No access allowed from Belarus
2a0b:8680::/29 Deny No access allowed from Belarus
2a0c:b1c0::/29 Deny No access allowed from Belarus
2a0d:2d00::/32 Deny No access allowed from Belarus
Origin: BY
