/**
 * Cloudflare Netblocks
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from the Cloudflare reverse proxy service.
 *
 * This file includes data created by Cloudflare, available from https://www.cloudflare.com/ips-v4
 * The source is publically available data.
 * This derivate is distributed under the Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) License
 * http://creativecommons.org/licenses/by-nc-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://github.com/macmathan
 *
 * Last updated 2018-05-11 00:54
 *
 * Version: CFRP-2018.130.995
 */
103.21.244.0/22 Deny Cloudhosted reverse proxy
103.22.200.0/22 Deny Cloudhosted reverse proxy
103.31.4.0/22 Deny Cloudhosted reverse proxy
104.16.0.0/12 Deny Cloudhosted reverse proxy
108.162.192.0/18 Deny Cloudhosted reverse proxy
131.0.72.0/22 Deny Cloudhosted reverse proxy
141.101.64.0/18 Deny Cloudhosted reverse proxy
162.158.0.0/15 Deny Cloudhosted reverse proxy
172.64.0.0/13 Deny Cloudhosted reverse proxy
173.245.48.0/20 Deny Cloudhosted reverse proxy
188.114.96.0/20 Deny Cloudhosted reverse proxy
190.93.240.0/20 Deny Cloudhosted reverse proxy
197.234.240.0/22 Deny Cloudhosted reverse proxy
198.41.128.0/17 Deny Cloudhosted reverse proxy
