/**
 * Cloudflare Netblocks
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from the Cloudflare reverse proxy service.
 *
 * This file includes data created by Cloudflare, available from https://www.cloudflare.com/ips-v6
 * The source is publically available data.
 * This derivate is distributed under the Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) License
 * http://creativecommons.org/licenses/by-nc-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://github.com/macmathan
 *
 * Last updated 2019-02-22 01:46
 *
 * Version: CFRP6-2019.52.074
 */
2a06:98c0::/29 Deny Cloudhosted reverse proxy
2c0f:f248::/32 Deny Cloudhosted reverse proxy
2400:cb00::/32 Deny Cloudhosted reverse proxy
2405:8100::/32 Deny Cloudhosted reverse proxy
2405:b500::/32 Deny Cloudhosted reverse proxy
2606:4700::/32 Deny Cloudhosted reverse proxy
2803:f800::/32 Deny Cloudhosted reverse proxy
