/**
 * Cuba netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Cuba
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: CU-2019.343.671
 */
2001:1340::/32 Deny No access allowed from Cuba
2001:1358::/32 Deny No access allowed from Cuba
2001:13c8::/32 Deny No access allowed from Cuba
2800:230::/32 Deny No access allowed from Cuba
2800:360::/32 Deny No access allowed from Cuba
2800:910::/32 Deny No access allowed from Cuba
2a01:ce94:1000::/36 Deny No access allowed from Cuba
2a01:ce94:2000::/35 Deny No access allowed from Cuba
2a01:ce94:4000::/34 Deny No access allowed from Cuba
2a01:ce94:8000::/33 Deny No access allowed from Cuba
2a03:b600:295::/98 Deny No access allowed from Cuba
2a03:b600:296::/98 Deny No access allowed from Cuba
2a03:b600:297::/98 Deny No access allowed from Cuba
2a03:b600:298::/98 Deny No access allowed from Cuba
2a03:b600:299::/98 Deny No access allowed from Cuba
Origin: CU
