/**
 * Cuba netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Cuba
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: CU-2019.343.671
 */
5.62.56.73/32 Deny No access allowed from Cuba
5.62.56.74/31 Deny No access allowed from Cuba
5.62.58.69/32 Deny No access allowed from Cuba
5.62.58.70/31 Deny No access allowed from Cuba
5.101.221.128/25 Deny No access allowed from Cuba
45.12.70.51/32 Deny No access allowed from Cuba
45.12.71.51/32 Deny No access allowed from Cuba
57.91.32.0/20 Deny No access allowed from Cuba
94.46.63.195/32 Deny No access allowed from Cuba
104.224.20.0/24 Deny No access allowed from Cuba
152.206.0.0/17 Deny No access allowed from Cuba
152.206.128.0/18 Deny No access allowed from Cuba
152.206.192.0/20 Deny No access allowed from Cuba
152.206.208.0/21 Deny No access allowed from Cuba
152.206.224.0/19 Deny No access allowed from Cuba
152.207.0.0/16 Deny No access allowed from Cuba
169.158.0.0/17 Deny No access allowed from Cuba
169.158.128.0/18 Deny No access allowed from Cuba
169.158.192.0/21 Deny No access allowed from Cuba
169.158.201.0/24 Deny No access allowed from Cuba
169.158.202.0/23 Deny No access allowed from Cuba
169.158.204.0/22 Deny No access allowed from Cuba
169.158.208.0/20 Deny No access allowed from Cuba
169.158.224.0/19 Deny No access allowed from Cuba
172.94.60.0/24 Deny No access allowed from Cuba
181.215.135.48/28 Deny No access allowed from Cuba
181.225.224.0/19 Deny No access allowed from Cuba
185.185.124.1/32 Deny No access allowed from Cuba
185.185.124.2/31 Deny No access allowed from Cuba
185.185.124.4/30 Deny No access allowed from Cuba
185.185.124.8/29 Deny No access allowed from Cuba
185.185.124.16/28 Deny No access allowed from Cuba
185.185.124.32/27 Deny No access allowed from Cuba
185.185.124.64/26 Deny No access allowed from Cuba
185.185.124.128/25 Deny No access allowed from Cuba
185.196.38.99/32 Deny No access allowed from Cuba
190.6.64.0/19 Deny No access allowed from Cuba
190.15.144.0/20 Deny No access allowed from Cuba
190.92.112.0/20 Deny No access allowed from Cuba
190.107.0.0/20 Deny No access allowed from Cuba
194.50.99.51/32 Deny No access allowed from Cuba
194.50.111.51/32 Deny No access allowed from Cuba
196.1.112.0/24 Deny No access allowed from Cuba
196.1.135.0/24 Deny No access allowed from Cuba
196.3.152.0/24 Deny No access allowed from Cuba
198.50.104.104/29 Deny No access allowed from Cuba
200.0.16.0/24 Deny No access allowed from Cuba
200.0.24.0/22 Deny No access allowed from Cuba
200.5.12.0/22 Deny No access allowed from Cuba
200.13.144.0/21 Deny No access allowed from Cuba
200.14.48.0/21 Deny No access allowed from Cuba
200.55.128.0/18 Deny No access allowed from Cuba
201.220.192.0/19 Deny No access allowed from Cuba
204.34.240.0/24 Deny No access allowed from Cuba
Origin: CU
