/**
 * Djibouti netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Djibouti
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: DJ-2019.343.671
 */
2001:4298::/32 Deny No access allowed from Djibouti
2001:43f8:9c0::/47 Deny No access allowed from Djibouti
2400:cb00:122::/48 Deny No access allowed from Djibouti
Origin: DJ
