/**
 * Djibouti netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Djibouti
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: DJ-2019.343.671
 */
5.62.61.96/30 Deny No access allowed from Djibouti
5.62.63.72/30 Deny No access allowed from Djibouti
41.189.224.0/19 Deny No access allowed from Djibouti
45.12.70.58/32 Deny No access allowed from Djibouti
45.12.71.58/32 Deny No access allowed from Djibouti
46.36.203.21/32 Deny No access allowed from Djibouti
46.36.203.22/31 Deny No access allowed from Djibouti
46.36.203.24/31 Deny No access allowed from Djibouti
80.78.16.128/30 Deny No access allowed from Djibouti
104.143.25.0/24 Deny No access allowed from Djibouti
105.16.20.0/23 Deny No access allowed from Djibouti
105.16.128.0/21 Deny No access allowed from Djibouti
105.18.16.0/20 Deny No access allowed from Djibouti
105.21.128.0/19 Deny No access allowed from Djibouti
105.27.104.0/23 Deny No access allowed from Djibouti
105.28.16.0/20 Deny No access allowed from Djibouti
154.66.245.0/24 Deny No access allowed from Djibouti
172.68.128.0/24 Deny No access allowed from Djibouti
194.50.99.58/32 Deny No access allowed from Djibouti
194.50.111.58/32 Deny No access allowed from Djibouti
196.49.10.0/24 Deny No access allowed from Djibouti
196.201.192.0/20 Deny No access allowed from Djibouti
196.223.38.0/24 Deny No access allowed from Djibouti
197.241.0.0/17 Deny No access allowed from Djibouti
217.78.64.0/20 Deny No access allowed from Djibouti
Origin: DJ
