/**
 * Algeria netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Algeria
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: DZ-2019.343.671
 */
5.62.61.244/30 Deny No access allowed from Algeria
5.62.63.240/30 Deny No access allowed from Algeria
31.132.52.0/24 Deny No access allowed from Algeria
41.77.176.0/21 Deny No access allowed from Algeria
41.96.0.0/13 Deny No access allowed from Algeria
41.104.0.0/14 Deny No access allowed from Algeria
41.108.0.0/16 Deny No access allowed from Algeria
41.109.0.0/18 Deny No access allowed from Algeria
41.109.64.0/19 Deny No access allowed from Algeria
41.109.96.0/20 Deny No access allowed from Algeria
41.109.112.0/22 Deny No access allowed from Algeria
41.109.116.0/24 Deny No access allowed from Algeria
41.109.118.0/23 Deny No access allowed from Algeria
41.109.120.0/21 Deny No access allowed from Algeria
41.109.128.0/17 Deny No access allowed from Algeria
41.110.0.0/15 Deny No access allowed from Algeria
41.191.252.0/22 Deny No access allowed from Algeria
41.200.0.0/15 Deny No access allowed from Algeria
41.210.64.0/18 Deny No access allowed from Algeria
41.220.144.0/20 Deny No access allowed from Algeria
41.221.16.0/20 Deny No access allowed from Algeria
41.223.176.0/22 Deny No access allowed from Algeria
41.223.236.0/22 Deny No access allowed from Algeria
45.12.70.62/32 Deny No access allowed from Algeria
45.12.71.62/32 Deny No access allowed from Algeria
45.59.177.0/24 Deny No access allowed from Algeria
57.82.32.0/20 Deny No access allowed from Algeria
68.168.124.224/29 Deny No access allowed from Algeria
80.88.12.0/22 Deny No access allowed from Algeria
80.246.0.0/20 Deny No access allowed from Algeria
80.249.64.0/20 Deny No access allowed from Algeria
81.31.193.108/30 Deny No access allowed from Algeria
82.195.187.21/32 Deny No access allowed from Algeria
82.196.25.0/24 Deny No access allowed from Algeria
85.203.22.32/28 Deny No access allowed from Algeria
92.39.244.224/28 Deny No access allowed from Algeria
92.39.251.160/27 Deny No access allowed from Algeria
95.168.185.183/32 Deny No access allowed from Algeria
104.167.224.0/24 Deny No access allowed from Algeria
105.96.0.0/12 Deny No access allowed from Algeria
105.235.128.0/20 Deny No access allowed from Algeria
129.45.0.0/17 Deny No access allowed from Algeria
154.73.92.0/22 Deny No access allowed from Algeria
154.121.0.0/16 Deny No access allowed from Algeria
154.127.96.0/20 Deny No access allowed from Algeria
154.240.0.0/16 Deny No access allowed from Algeria
154.241.0.0/18 Deny No access allowed from Algeria
154.241.64.0/20 Deny No access allowed from Algeria
154.241.80.0/21 Deny No access allowed from Algeria
154.241.88.0/23 Deny No access allowed from Algeria
154.241.90.0/24 Deny No access allowed from Algeria
154.241.92.0/22 Deny No access allowed from Algeria
154.241.96.0/19 Deny No access allowed from Algeria
154.241.128.0/17 Deny No access allowed from Algeria
154.242.0.0/15 Deny No access allowed from Algeria
154.244.0.0/14 Deny No access allowed from Algeria
154.248.0.0/13 Deny No access allowed from Algeria
157.167.97.0/24 Deny No access allowed from Algeria
168.253.96.0/20 Deny No access allowed from Algeria
172.94.64.0/24 Deny No access allowed from Algeria
178.208.176.0/24 Deny No access allowed from Algeria
181.215.138.40/29 Deny No access allowed from Algeria
192.1.168.254/32 Deny No access allowed from Algeria
192.52.232.0/24 Deny No access allowed from Algeria
192.245.148.0/24 Deny No access allowed from Algeria
193.41.146.0/23 Deny No access allowed from Algeria
193.194.64.0/19 Deny No access allowed from Algeria
194.50.99.62/32 Deny No access allowed from Algeria
194.50.111.62/32 Deny No access allowed from Algeria
195.24.80.0/21 Deny No access allowed from Algeria
195.39.218.0/23 Deny No access allowed from Algeria
196.11.75.0/24 Deny No access allowed from Algeria
196.20.64.0/18 Deny No access allowed from Algeria
196.29.40.0/22 Deny No access allowed from Algeria
196.32.16.0/20 Deny No access allowed from Algeria
196.41.224.0/19 Deny No access allowed from Algeria
196.46.248.0/21 Deny No access allowed from Algeria
197.112.0.0/13 Deny No access allowed from Algeria
197.140.0.0/14 Deny No access allowed from Algeria
197.200.0.0/13 Deny No access allowed from Algeria
198.50.100.184/29 Deny No access allowed from Algeria
198.50.108.136/29 Deny No access allowed from Algeria
204.214.85.120/32 Deny No access allowed from Algeria
206.123.159.128/25 Deny No access allowed from Algeria
213.140.59.0/24 Deny No access allowed from Algeria
213.179.160.0/19 Deny No access allowed from Algeria
217.156.142.96/29 Deny No access allowed from Algeria
217.156.158.184/29 Deny No access allowed from Algeria
Origin: DZ
