/**
 * Ecuador netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Ecuador
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: EC-2019.343.671
 */
2001:13b0:d000:3205::/64 Deny No access allowed from Ecuador
2001:13b0:d002::/52 Deny No access allowed from Ecuador
2001:13c7:6006::/48 Deny No access allowed from Ecuador
2001:13c7:6f00::/40 Deny No access allowed from Ecuador
2400:cb00:95::/48 Deny No access allowed from Ecuador
2606:2800:420d::/48 Deny No access allowed from Ecuador
2620:0:876:9200::/56 Deny No access allowed from Ecuador
2800:68::/32 Deny No access allowed from Ecuador
2800:130::/32 Deny No access allowed from Ecuador
2800:2a0::/32 Deny No access allowed from Ecuador
2800:2f0::/32 Deny No access allowed from Ecuador
2800:370::/32 Deny No access allowed from Ecuador
2800:400::/32 Deny No access allowed from Ecuador
2800:430::/32 Deny No access allowed from Ecuador
2800:440::/32 Deny No access allowed from Ecuador
2800:4f0::/32 Deny No access allowed from Ecuador
2800:5f0::/32 Deny No access allowed from Ecuador
2800:660::/31 Deny No access allowed from Ecuador
2800:830::/31 Deny No access allowed from Ecuador
2800:9a0::/29 Deny No access allowed from Ecuador
2800:b30::/31 Deny No access allowed from Ecuador
2800:bf0::/32 Deny No access allowed from Ecuador
2800:c10::/32 Deny No access allowed from Ecuador
2801:0:20::/48 Deny No access allowed from Ecuador
2801:0:60::/46 Deny No access allowed from Ecuador
2801:0:270::/48 Deny No access allowed from Ecuador
2801:0:410::/48 Deny No access allowed from Ecuador
2801:0:420::/48 Deny No access allowed from Ecuador
2801:0:4d0::/48 Deny No access allowed from Ecuador
2801:13:4800::/48 Deny No access allowed from Ecuador
2801:13:7000::/48 Deny No access allowed from Ecuador
2801:15::/48 Deny No access allowed from Ecuador
2801:16:4800::/48 Deny No access allowed from Ecuador
2801:19:8000::/48 Deny No access allowed from Ecuador
2801:1a:3000::/48 Deny No access allowed from Ecuador
2801:1a:4800::/48 Deny No access allowed from Ecuador
2801:1b:4800::/48 Deny No access allowed from Ecuador
2801:1c:8000::/48 Deny No access allowed from Ecuador
2801:1c:f000::/48 Deny No access allowed from Ecuador
2801:1e::/48 Deny No access allowed from Ecuador
2801:1e:4800::/48 Deny No access allowed from Ecuador
2801:1e:5000::/48 Deny No access allowed from Ecuador
2801:1e:8800::/48 Deny No access allowed from Ecuador
2801:1f:4800::/48 Deny No access allowed from Ecuador
2802:3:6000::/35 Deny No access allowed from Ecuador
2803:480::/32 Deny No access allowed from Ecuador
2803:b00::/32 Deny No access allowed from Ecuador
2803:ba0::/32 Deny No access allowed from Ecuador
2803:fc0::/32 Deny No access allowed from Ecuador
2803:10e0::/32 Deny No access allowed from Ecuador
2803:1160::/32 Deny No access allowed from Ecuador
2803:1360::/32 Deny No access allowed from Ecuador
2803:1c20::/32 Deny No access allowed from Ecuador
2803:1f60::/32 Deny No access allowed from Ecuador
2803:2200::/32 Deny No access allowed from Ecuador
2803:2220::/32 Deny No access allowed from Ecuador
2803:2540::/32 Deny No access allowed from Ecuador
2803:27c0::/32 Deny No access allowed from Ecuador
2803:2920::/32 Deny No access allowed from Ecuador
2803:2a60::/32 Deny No access allowed from Ecuador
2803:2c20::/32 Deny No access allowed from Ecuador
2803:2e00::/32 Deny No access allowed from Ecuador
2803:3020::/32 Deny No access allowed from Ecuador
2803:37a0::/32 Deny No access allowed from Ecuador
2803:3920::/32 Deny No access allowed from Ecuador
2803:3c00::/32 Deny No access allowed from Ecuador
2803:3c20::/32 Deny No access allowed from Ecuador
2803:3f60::/32 Deny No access allowed from Ecuador
2803:4180::/32 Deny No access allowed from Ecuador
2803:46c0::/32 Deny No access allowed from Ecuador
2803:4c00::/32 Deny No access allowed from Ecuador
2803:4ca0::/32 Deny No access allowed from Ecuador
2803:4e60::/32 Deny No access allowed from Ecuador
2803:51a0::/32 Deny No access allowed from Ecuador
2803:5320::/32 Deny No access allowed from Ecuador
2803:56a0::/32 Deny No access allowed from Ecuador
2803:5740::/32 Deny No access allowed from Ecuador
2803:57c0::/32 Deny No access allowed from Ecuador
2803:59c0::/32 Deny No access allowed from Ecuador
2803:5c60::/32 Deny No access allowed from Ecuador
2803:5f80::/32 Deny No access allowed from Ecuador
2803:62c0::/32 Deny No access allowed from Ecuador
2803:6320::/32 Deny No access allowed from Ecuador
2803:6420::/32 Deny No access allowed from Ecuador
2803:6520::/32 Deny No access allowed from Ecuador
2803:6620::/32 Deny No access allowed from Ecuador
2803:67c0::/32 Deny No access allowed from Ecuador
2803:6a00::/32 Deny No access allowed from Ecuador
2803:6b60::/32 Deny No access allowed from Ecuador
2803:6ec0::/32 Deny No access allowed from Ecuador
2803:70a0::/32 Deny No access allowed from Ecuador
2803:7260::/32 Deny No access allowed from Ecuador
2803:7c20::/32 Deny No access allowed from Ecuador
2803:81c0::/32 Deny No access allowed from Ecuador
2803:8300::/32 Deny No access allowed from Ecuador
2803:8420::/32 Deny No access allowed from Ecuador
2803:8520::/32 Deny No access allowed from Ecuador
2803:87c0::/32 Deny No access allowed from Ecuador
2803:8820::/32 Deny No access allowed from Ecuador
2803:8c20::/32 Deny No access allowed from Ecuador
2803:92a0::/32 Deny No access allowed from Ecuador
2803:97a0::/32 Deny No access allowed from Ecuador
2803:9ac0::/32 Deny No access allowed from Ecuador
2803:9c20::/32 Deny No access allowed from Ecuador
2803:9cc0::/32 Deny No access allowed from Ecuador
2803:9dc0::/32 Deny No access allowed from Ecuador
2803:a0a0::/32 Deny No access allowed from Ecuador
2803:a240::/32 Deny No access allowed from Ecuador
2803:a400::/32 Deny No access allowed from Ecuador
2803:a660::/32 Deny No access allowed from Ecuador
2803:a820::/32 Deny No access allowed from Ecuador
2803:a8a0::/32 Deny No access allowed from Ecuador
2803:aa20::/32 Deny No access allowed from Ecuador
2803:ab60::/32 Deny No access allowed from Ecuador
2803:abc0::/32 Deny No access allowed from Ecuador
2803:ac60::/32 Deny No access allowed from Ecuador
2803:af40::/32 Deny No access allowed from Ecuador
2803:b2c0::/32 Deny No access allowed from Ecuador
2803:b420::/32 Deny No access allowed from Ecuador
2803:b4c0::/32 Deny No access allowed from Ecuador
2803:b820::/32 Deny No access allowed from Ecuador
2803:b9c0:9500::/40 Deny No access allowed from Ecuador
2803:b9c0:9a00::/40 Deny No access allowed from Ecuador
2803:bbc0::/32 Deny No access allowed from Ecuador
2803:bc20::/32 Deny No access allowed from Ecuador
2803:bf20::/32 Deny No access allowed from Ecuador
2803:bfc0::/32 Deny No access allowed from Ecuador
2803:c220::/32 Deny No access allowed from Ecuador
2803:c280::/32 Deny No access allowed from Ecuador
2803:c2c0::/32 Deny No access allowed from Ecuador
2803:c420::/32 Deny No access allowed from Ecuador
2803:c5c0::/32 Deny No access allowed from Ecuador
2803:c720::/32 Deny No access allowed from Ecuador
2803:cb20::/32 Deny No access allowed from Ecuador
2803:cc20::/32 Deny No access allowed from Ecuador
2803:d180::/32 Deny No access allowed from Ecuador
2803:d220::/32 Deny No access allowed from Ecuador
2803:d560::/32 Deny No access allowed from Ecuador
2803:d8a0::/32 Deny No access allowed from Ecuador
2803:dda0::/32 Deny No access allowed from Ecuador
2803:de60::/32 Deny No access allowed from Ecuador
2803:dea0::/32 Deny No access allowed from Ecuador
2803:e0e0::/32 Deny No access allowed from Ecuador
2803:e220::/32 Deny No access allowed from Ecuador
2803:e360::/32 Deny No access allowed from Ecuador
2803:e620::/32 Deny No access allowed from Ecuador
2803:ec20::/32 Deny No access allowed from Ecuador
2803:ec40::/32 Deny No access allowed from Ecuador
2803:efc0::/32 Deny No access allowed from Ecuador
2803:f060::/32 Deny No access allowed from Ecuador
2803:f0a0::/32 Deny No access allowed from Ecuador
2803:f6a0::/32 Deny No access allowed from Ecuador
2803:f760::/32 Deny No access allowed from Ecuador
2803:f920::/32 Deny No access allowed from Ecuador
2803:fbc0::/32 Deny No access allowed from Ecuador
2803:fc20::/32 Deny No access allowed from Ecuador
2803:fd60::/32 Deny No access allowed from Ecuador
2803:ff60::/32 Deny No access allowed from Ecuador
2a0e:cd00::/32 Deny No access allowed from Ecuador
Origin: EC
