/**
 * Egypt netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Egypt
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: EG-2019.343.671
 */
2001:500:15:5500::/56 Deny No access allowed from Egypt
2001:4220::/32 Deny No access allowed from Egypt
2001:42b8::/32 Deny No access allowed from Egypt
2001:4300::/32 Deny No access allowed from Egypt
2001:4388::/32 Deny No access allowed from Egypt
2001:43c8::/32 Deny No access allowed from Egypt
2001:43f8:2e0::/48 Deny No access allowed from Egypt
2400:cb00:62::/48 Deny No access allowed from Egypt
2620:171:55::/48 Deny No access allowed from Egypt
2620:171:f6::/48 Deny No access allowed from Egypt
2a00:79e0:ab::/48 Deny No access allowed from Egypt
2a00:79e0:ffe2:c300::/56 Deny No access allowed from Egypt
2a00:79e1:abd:b00::/56 Deny No access allowed from Egypt
2a0a:90c0:1088::/48 Deny No access allowed from Egypt
2a0e:fd45:1337::/48 Deny No access allowed from Egypt
2c0e::/20 Deny No access allowed from Egypt
2c0f:f0b0::/32 Deny No access allowed from Egypt
2c0f:fc40::/32 Deny No access allowed from Egypt
2c0f:fc88::/31 Deny No access allowed from Egypt
2c0f:fee0::/32 Deny No access allowed from Egypt
Origin: EG
