/**
 * Google Appengine Netblocks
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from the Google cloud.
 *
 * This file includes data created by Google, available as described on https://cloud.google.com/appengine/kb/#static-ip
 * The source is publically available data.
 * This derivate is distributed under the Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) License
 * http://creativecommons.org/licenses/by-nc-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://github.com/macmathan
 *
 * Last updated 2018-05-13 14:34
 *
 * Version: GCP-2018.132.565
 */
2600:1900::/35 Deny Cloud
