/**
 * Kyrgyzstan netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Kyrgyzstan
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: KG-2019.343.671
 */
5.57.8.0/21 Deny No access allowed from Kyrgyzstan
5.59.11.0/24 Deny No access allowed from Kyrgyzstan
5.62.60.204/30 Deny No access allowed from Kyrgyzstan
5.62.62.196/30 Deny No access allowed from Kyrgyzstan
31.29.0.0/19 Deny No access allowed from Kyrgyzstan
31.186.48.0/21 Deny No access allowed from Kyrgyzstan
31.192.248.0/21 Deny No access allowed from Kyrgyzstan
37.218.128.0/18 Deny No access allowed from Kyrgyzstan
45.12.70.117/32 Deny No access allowed from Kyrgyzstan
45.12.71.117/32 Deny No access allowed from Kyrgyzstan
45.59.147.0/24 Deny No access allowed from Kyrgyzstan
45.129.130.0/23 Deny No access allowed from Kyrgyzstan
45.130.214.0/23 Deny No access allowed from Kyrgyzstan
46.36.200.241/32 Deny No access allowed from Kyrgyzstan
46.36.200.242/31 Deny No access allowed from Kyrgyzstan
46.36.200.244/31 Deny No access allowed from Kyrgyzstan
46.226.208.0/21 Deny No access allowed from Kyrgyzstan
46.235.72.0/22 Deny No access allowed from Kyrgyzstan
46.251.192.0/19 Deny No access allowed from Kyrgyzstan
57.92.160.0/20 Deny No access allowed from Kyrgyzstan
62.4.108.0/24 Deny No access allowed from Kyrgyzstan
66.102.9.19/32 Deny No access allowed from Kyrgyzstan
77.95.56.0/21 Deny No access allowed from Kyrgyzstan
77.220.204.0/24 Deny No access allowed from Kyrgyzstan
77.235.0.0/19 Deny No access allowed from Kyrgyzstan
80.72.176.0/20 Deny No access allowed from Kyrgyzstan
81.20.16.0/20 Deny No access allowed from Kyrgyzstan
81.88.192.0/20 Deny No access allowed from Kyrgyzstan
85.113.0.0/19 Deny No access allowed from Kyrgyzstan
89.237.192.0/18 Deny No access allowed from Kyrgyzstan
91.132.224.0/22 Deny No access allowed from Kyrgyzstan
91.192.64.0/22 Deny No access allowed from Kyrgyzstan
91.205.48.0/22 Deny No access allowed from Kyrgyzstan
91.207.28.0/23 Deny No access allowed from Kyrgyzstan
91.213.233.0/24 Deny No access allowed from Kyrgyzstan
91.229.224.0/23 Deny No access allowed from Kyrgyzstan
91.247.56.0/21 Deny No access allowed from Kyrgyzstan
92.62.64.0/20 Deny No access allowed from Kyrgyzstan
92.245.96.0/19 Deny No access allowed from Kyrgyzstan
93.157.224.0/21 Deny No access allowed from Kyrgyzstan
93.170.8.0/24 Deny No access allowed from Kyrgyzstan
93.171.76.0/23 Deny No access allowed from Kyrgyzstan
94.143.192.0/21 Deny No access allowed from Kyrgyzstan
95.46.154.0/24 Deny No access allowed from Kyrgyzstan
95.87.64.0/19 Deny No access allowed from Kyrgyzstan
95.215.244.0/22 Deny No access allowed from Kyrgyzstan
109.71.224.0/21 Deny No access allowed from Kyrgyzstan
109.201.160.0/19 Deny No access allowed from Kyrgyzstan
146.120.212.0/23 Deny No access allowed from Kyrgyzstan
146.120.245.0/24 Deny No access allowed from Kyrgyzstan
155.254.204.0/24 Deny No access allowed from Kyrgyzstan
158.181.0.0/19 Deny No access allowed from Kyrgyzstan
158.181.128.0/17 Deny No access allowed from Kyrgyzstan
176.123.224.0/19 Deny No access allowed from Kyrgyzstan
176.126.164.0/22 Deny No access allowed from Kyrgyzstan
178.171.44.0/23 Deny No access allowed from Kyrgyzstan
178.216.208.0/21 Deny No access allowed from Kyrgyzstan
178.217.168.0/21 Deny No access allowed from Kyrgyzstan
181.215.137.64/28 Deny No access allowed from Kyrgyzstan
185.1.110.0/24 Deny No access allowed from Kyrgyzstan
185.1.151.0/24 Deny No access allowed from Kyrgyzstan
185.20.120.0/22 Deny No access allowed from Kyrgyzstan
185.29.184.0/22 Deny No access allowed from Kyrgyzstan
185.48.136.0/22 Deny No access allowed from Kyrgyzstan
185.52.139.0/24 Deny No access allowed from Kyrgyzstan
185.53.104.0/22 Deny No access allowed from Kyrgyzstan
185.53.228.0/22 Deny No access allowed from Kyrgyzstan
185.54.252.0/22 Deny No access allowed from Kyrgyzstan
185.66.252.0/22 Deny No access allowed from Kyrgyzstan
185.67.254.0/23 Deny No access allowed from Kyrgyzstan
185.88.32.0/22 Deny No access allowed from Kyrgyzstan
185.117.148.0/22 Deny No access allowed from Kyrgyzstan
185.138.100.0/22 Deny No access allowed from Kyrgyzstan
185.138.184.0/22 Deny No access allowed from Kyrgyzstan
185.157.136.0/22 Deny No access allowed from Kyrgyzstan
185.161.48.0/22 Deny No access allowed from Kyrgyzstan
185.211.228.0/22 Deny No access allowed from Kyrgyzstan
185.229.36.0/22 Deny No access allowed from Kyrgyzstan
193.106.48.0/22 Deny No access allowed from Kyrgyzstan
193.151.226.0/24 Deny No access allowed from Kyrgyzstan
194.50.111.117/32 Deny No access allowed from Kyrgyzstan
194.152.36.0/23 Deny No access allowed from Kyrgyzstan
194.176.111.0/24 Deny No access allowed from Kyrgyzstan
195.38.160.0/19 Deny No access allowed from Kyrgyzstan
195.54.180.0/23 Deny No access allowed from Kyrgyzstan
195.114.240.0/20 Deny No access allowed from Kyrgyzstan
195.216.237.0/24 Deny No access allowed from Kyrgyzstan
206.123.151.128/25 Deny No access allowed from Kyrgyzstan
212.2.224.0/19 Deny No access allowed from Kyrgyzstan
212.42.96.0/19 Deny No access allowed from Kyrgyzstan
212.97.0.0/19 Deny No access allowed from Kyrgyzstan
212.112.96.0/19 Deny No access allowed from Kyrgyzstan
212.241.0.0/19 Deny No access allowed from Kyrgyzstan
213.109.64.0/21 Deny No access allowed from Kyrgyzstan
213.145.128.0/19 Deny No access allowed from Kyrgyzstan
217.29.16.0/20 Deny No access allowed from Kyrgyzstan
Origin: KG
