/**
 * Kyrgyzstan netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Kyrgyzstan
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: KG-2019.343.671
 */
2001:67c:12e0::/48 Deny No access allowed from Kyrgyzstan
2001:7f8:3c::/48 Deny No access allowed from Kyrgyzstan
2001:7f8:e5::/48 Deny No access allowed from Kyrgyzstan
2a00:47a0::/32 Deny No access allowed from Kyrgyzstan
2a00:5700::/32 Deny No access allowed from Kyrgyzstan
2a00:7160::/32 Deny No access allowed from Kyrgyzstan
2a00:b020::/32 Deny No access allowed from Kyrgyzstan
2a01:96a0::/32 Deny No access allowed from Kyrgyzstan
2a01:9d00::/32 Deny No access allowed from Kyrgyzstan
2a01:bfa0::/32 Deny No access allowed from Kyrgyzstan
2a02:820::/32 Deny No access allowed from Kyrgyzstan
2a03:6947:1000::/40 Deny No access allowed from Kyrgyzstan
2a04:5200:c068::/48 Deny No access allowed from Kyrgyzstan
2a04:5600::/29 Deny No access allowed from Kyrgyzstan
2a04:b340::/29 Deny No access allowed from Kyrgyzstan
2a05:c880::/29 Deny No access allowed from Kyrgyzstan
2a0b:6e40::/29 Deny No access allowed from Kyrgyzstan
2a0b:d7c0::/29 Deny No access allowed from Kyrgyzstan
2a0c:de80::/48 Deny No access allowed from Kyrgyzstan
2a0d:dd00::/29 Deny No access allowed from Kyrgyzstan
2a0f:5240::/32 Deny No access allowed from Kyrgyzstan
Origin: KG
