/**
 * Cambodia netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Cambodia
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: KH-2019.343.671
 */
2001:dd8:1e::/48 Deny No access allowed from Cambodia
2001:de8:1d::/48 Deny No access allowed from Cambodia
2001:df0:3480::/48 Deny No access allowed from Cambodia
2001:df0:5080::/48 Deny No access allowed from Cambodia
2001:df0:5880::/48 Deny No access allowed from Cambodia
2001:df0:9f00::/48 Deny No access allowed from Cambodia
2001:df0:dd00::/48 Deny No access allowed from Cambodia
2001:df0:ff80::/48 Deny No access allowed from Cambodia
2001:df1:2280::/48 Deny No access allowed from Cambodia
2001:df1:5780::/48 Deny No access allowed from Cambodia
2001:df1:c701::/48 Deny No access allowed from Cambodia
2001:df2:a500::/48 Deny No access allowed from Cambodia
2001:df3:5900::/48 Deny No access allowed from Cambodia
2400:4880::/32 Deny No access allowed from Cambodia
2400:cb00:144::/48 Deny No access allowed from Cambodia
2401:3e00::/32 Deny No access allowed from Cambodia
2401:4d80::/32 Deny No access allowed from Cambodia
2401:5bc0::/32 Deny No access allowed from Cambodia
2401:7540::/32 Deny No access allowed from Cambodia
2401:9700::/32 Deny No access allowed from Cambodia
2401:a700::/32 Deny No access allowed from Cambodia
2401:cb00::/32 Deny No access allowed from Cambodia
2401:ccc0::/32 Deny No access allowed from Cambodia
2401:d4c0::/32 Deny No access allowed from Cambodia
2402:4c0::/32 Deny No access allowed from Cambodia
2402:25c0::/32 Deny No access allowed from Cambodia
2402:4740::/32 Deny No access allowed from Cambodia
2402:5100::/32 Deny No access allowed from Cambodia
2402:74c0::/32 Deny No access allowed from Cambodia
2402:7a40::/32 Deny No access allowed from Cambodia
2402:b340::/32 Deny No access allowed from Cambodia
2402:c100::/32 Deny No access allowed from Cambodia
2402:cd40::/32 Deny No access allowed from Cambodia
2402:eb40::/32 Deny No access allowed from Cambodia
2403:1600::/32 Deny No access allowed from Cambodia
2403:1c40::/32 Deny No access allowed from Cambodia
2403:2840::/32 Deny No access allowed from Cambodia
2403:4140::/32 Deny No access allowed from Cambodia
2403:45c0::/32 Deny No access allowed from Cambodia
2403:6600::/32 Deny No access allowed from Cambodia
2403:7140::/32 Deny No access allowed from Cambodia
2403:7500::/32 Deny No access allowed from Cambodia
2403:bbc0::/32 Deny No access allowed from Cambodia
2404:300::/32 Deny No access allowed from Cambodia
2404:700::/32 Deny No access allowed from Cambodia
2404:2c40::/32 Deny No access allowed from Cambodia
2404:68c0::/32 Deny No access allowed from Cambodia
2404:7c40::/32 Deny No access allowed from Cambodia
2404:83c0::/32 Deny No access allowed from Cambodia
2404:8a40::/32 Deny No access allowed from Cambodia
2404:9240::/32 Deny No access allowed from Cambodia
2404:9940::/32 Deny No access allowed from Cambodia
2404:a540::/32 Deny No access allowed from Cambodia
2404:b300::/32 Deny No access allowed from Cambodia
2404:bb80::/32 Deny No access allowed from Cambodia
2404:cc00::/32 Deny No access allowed from Cambodia
2404:e980::/32 Deny No access allowed from Cambodia
2404:eac0::/32 Deny No access allowed from Cambodia
2405:b00::/32 Deny No access allowed from Cambodia
2405:1a00::/32 Deny No access allowed from Cambodia
2405:2940::/32 Deny No access allowed from Cambodia
2405:3900::/32 Deny No access allowed from Cambodia
2405:8380::/32 Deny No access allowed from Cambodia
2405:aa00::/32 Deny No access allowed from Cambodia
2405:da00::/32 Deny No access allowed from Cambodia
2405:e280::/32 Deny No access allowed from Cambodia
2405:f500::/32 Deny No access allowed from Cambodia
2405:fa00::/32 Deny No access allowed from Cambodia
2406:b100::/32 Deny No access allowed from Cambodia
2407:5e00::/32 Deny No access allowed from Cambodia
2407:6680::/32 Deny No access allowed from Cambodia
2407:8180::/32 Deny No access allowed from Cambodia
2407:c180::/32 Deny No access allowed from Cambodia
2620:0:876:7600::/56 Deny No access allowed from Cambodia
Origin: KH
