/**
 * North Korea netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from North Korea
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: KP-2019.343.671
 */
5.62.56.161/32 Deny No access allowed from North Korea
5.62.56.162/31 Deny No access allowed from North Korea
5.62.61.65/32 Deny No access allowed from North Korea
5.62.61.66/31 Deny No access allowed from North Korea
45.12.70.122/32 Deny No access allowed from North Korea
45.12.71.122/32 Deny No access allowed from North Korea
82.102.0.129/32 Deny No access allowed from North Korea
88.151.117.0/24 Deny No access allowed from North Korea
94.46.49.204/32 Deny No access allowed from North Korea
175.45.176.0/22 Deny No access allowed from North Korea
185.51.35.159/32 Deny No access allowed from North Korea
185.196.36.83/32 Deny No access allowed from North Korea
188.114.227.151/32 Deny No access allowed from North Korea
194.50.99.122/32 Deny No access allowed from North Korea
194.50.111.122/32 Deny No access allowed from North Korea
202.72.96.4/30 Deny No access allowed from North Korea
210.52.109.0/24 Deny No access allowed from North Korea
Origin: KP
