/**
 * North Korea netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from North Korea
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: KP-2019.343.671
 */
2a0c:b641:211::/48 Deny No access allowed from North Korea
2a0c:b641:21f::/48 Deny No access allowed from North Korea
Origin: KP
