/**
 * Kazakhstan netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Kazakhstan
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: KZ-2019.343.671
 */
2001:67c:14a8::/48 Deny No access allowed from Kazakhstan
2a00:12f8::/32 Deny No access allowed from Kazakhstan
2a00:1a08::/32 Deny No access allowed from Kazakhstan
2a00:5da0::/32 Deny No access allowed from Kazakhstan
2a00:8d20::/32 Deny No access allowed from Kazakhstan
2a00:ab40::/32 Deny No access allowed from Kazakhstan
2a00:cfe0::/32 Deny No access allowed from Kazakhstan
2a01:42e0::/32 Deny No access allowed from Kazakhstan
2a01:4b40::/32 Deny No access allowed from Kazakhstan
2a01:4d40::/32 Deny No access allowed from Kazakhstan
2a01:68c0::/32 Deny No access allowed from Kazakhstan
2a01:7640::/32 Deny No access allowed from Kazakhstan
2a01:8ce0::/32 Deny No access allowed from Kazakhstan
2a01:99e0::/32 Deny No access allowed from Kazakhstan
2a01:b0c0::/32 Deny No access allowed from Kazakhstan
2a02:6bf:fff0:2200::/60 Deny No access allowed from Kazakhstan
2a02:4400::/32 Deny No access allowed from Kazakhstan
2a02:50c0::/29 Deny No access allowed from Kazakhstan
2a02:7300::/32 Deny No access allowed from Kazakhstan
2a02:7b60::/32 Deny No access allowed from Kazakhstan
2a03:32c0::/32 Deny No access allowed from Kazakhstan
2a03:4ac0::/32 Deny No access allowed from Kazakhstan
2a03:6340::/32 Deny No access allowed from Kazakhstan
2a03:6947:f00::/40 Deny No access allowed from Kazakhstan
2a03:7b20::/32 Deny No access allowed from Kazakhstan
2a03:a300::/32 Deny No access allowed from Kazakhstan
2a04:3a80::/29 Deny No access allowed from Kazakhstan
2a04:4f40::/29 Deny No access allowed from Kazakhstan
2a04:5140::/29 Deny No access allowed from Kazakhstan
2a05:e040::/29 Deny No access allowed from Kazakhstan
2a05:f040::/29 Deny No access allowed from Kazakhstan
2a06:580::/29 Deny No access allowed from Kazakhstan
2a06:940::/29 Deny No access allowed from Kazakhstan
2a06:1a00::/29 Deny No access allowed from Kazakhstan
2a06:6780::/29 Deny No access allowed from Kazakhstan
2a06:8900::/29 Deny No access allowed from Kazakhstan
2a07:1e00::/29 Deny No access allowed from Kazakhstan
2a07:dd80::/29 Deny No access allowed from Kazakhstan
2a09:3200::/29 Deny No access allowed from Kazakhstan
2a09:6140::/29 Deny No access allowed from Kazakhstan
2a0a:7380::/29 Deny No access allowed from Kazakhstan
2a0b:abc0::/29 Deny No access allowed from Kazakhstan
2a0c:f080::/30 Deny No access allowed from Kazakhstan
2a0d:b200::/29 Deny No access allowed from Kazakhstan
2a0d:bcc0::/29 Deny No access allowed from Kazakhstan
2a0d:c6c0::/29 Deny No access allowed from Kazakhstan
2a0e:6600::/29 Deny No access allowed from Kazakhstan
2a0e:9340::/29 Deny No access allowed from Kazakhstan
2a0e:d100::/29 Deny No access allowed from Kazakhstan
2a0e:d280::/29 Deny No access allowed from Kazakhstan
2a0e:db80::/29 Deny No access allowed from Kazakhstan
2a0f:fd80::/29 Deny No access allowed from Kazakhstan
Origin: KZ
