/**
 * Laos netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Laos
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: LA-2019.343.671
 */
2001:df0:bf::/48 Deny No access allowed from Laos
2001:df0:df80::/48 Deny No access allowed from Laos
2001:df4:6400::/48 Deny No access allowed from Laos
2001:df4:b900::/48 Deny No access allowed from Laos
2400:81c0::/32 Deny No access allowed from Laos
2400:aa00::/32 Deny No access allowed from Laos
2400:c180::/32 Deny No access allowed from Laos
2402:6840::/32 Deny No access allowed from Laos
2402:8c80::/32 Deny No access allowed from Laos
2403:c0::/32 Deny No access allowed from Laos
2403:500::/32 Deny No access allowed from Laos
2404:2e00::/32 Deny No access allowed from Laos
2404:adc0::/32 Deny No access allowed from Laos
2404:c200::/32 Deny No access allowed from Laos
2405:1c40::/32 Deny No access allowed from Laos
2407:4280::/32 Deny No access allowed from Laos
2a06:8e80::/29 Deny No access allowed from Laos
Origin: LA
