/**
 * Laos netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Laos
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: LA-2019.343.671
 */
5.62.60.208/30 Deny No access allowed from Laos
5.62.62.200/30 Deny No access allowed from Laos
5.253.184.0/23 Deny No access allowed from Laos
43.224.36.0/22 Deny No access allowed from Laos
43.228.84.0/22 Deny No access allowed from Laos
43.252.244.0/22 Deny No access allowed from Laos
45.12.70.127/32 Deny No access allowed from Laos
45.12.71.127/32 Deny No access allowed from Laos
45.59.188.0/24 Deny No access allowed from Laos
46.244.29.96/28 Deny No access allowed from Laos
64.64.121.224/29 Deny No access allowed from Laos
101.78.8.0/21 Deny No access allowed from Laos
103.1.28.0/22 Deny No access allowed from Laos
103.1.232.0/22 Deny No access allowed from Laos
103.13.88.0/22 Deny No access allowed from Laos
103.26.103.0/24 Deny No access allowed from Laos
103.43.76.0/22 Deny No access allowed from Laos
103.59.52.0/22 Deny No access allowed from Laos
103.67.20.0/22 Deny No access allowed from Laos
103.82.56.0/22 Deny No access allowed from Laos
103.95.24.0/22 Deny No access allowed from Laos
103.109.116.0/22 Deny No access allowed from Laos
103.112.191.0/24 Deny No access allowed from Laos
103.114.146.0/23 Deny No access allowed from Laos
103.137.88.0/22 Deny No access allowed from Laos
103.138.142.0/24 Deny No access allowed from Laos
103.140.246.0/23 Deny No access allowed from Laos
103.145.48.0/24 Deny No access allowed from Laos
103.205.16.0/22 Deny No access allowed from Laos
103.210.14.0/24 Deny No access allowed from Laos
103.228.101.0/24 Deny No access allowed from Laos
103.228.252.0/22 Deny No access allowed from Laos
103.232.80.0/22 Deny No access allowed from Laos
103.240.240.0/22 Deny No access allowed from Laos
103.245.164.0/23 Deny No access allowed from Laos
103.245.166.0/24 Deny No access allowed from Laos
103.249.156.0/22 Deny No access allowed from Laos
114.129.24.0/21 Deny No access allowed from Laos
115.84.64.0/18 Deny No access allowed from Laos
139.5.156.0/22 Deny No access allowed from Laos
139.81.42.0/23 Deny No access allowed from Laos
155.254.209.0/24 Deny No access allowed from Laos
157.119.180.0/22 Deny No access allowed from Laos
157.167.32.0/24 Deny No access allowed from Laos
160.181.242.0/24 Deny No access allowed from Laos
163.198.170.0/24 Deny No access allowed from Laos
163.198.171.0/25 Deny No access allowed from Laos
172.110.218.128/25 Deny No access allowed from Laos
180.131.148.0/22 Deny No access allowed from Laos
183.182.96.0/19 Deny No access allowed from Laos
185.19.104.0/22 Deny No access allowed from Laos
194.50.111.127/32 Deny No access allowed from Laos
195.158.206.0/24 Deny No access allowed from Laos
195.158.207.0/25 Deny No access allowed from Laos
202.9.76.0/23 Deny No access allowed from Laos
202.62.96.0/20 Deny No access allowed from Laos
202.123.176.0/21 Deny No access allowed from Laos
202.136.240.0/21 Deny No access allowed from Laos
202.137.128.0/19 Deny No access allowed from Laos
202.144.184.0/21 Deny No access allowed from Laos
203.76.252.0/22 Deny No access allowed from Laos
203.110.64.0/20 Deny No access allowed from Laos
206.123.153.0/25 Deny No access allowed from Laos
Origin: LA
