/**
 * Pakistan netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Pakistan
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: PK-2019.343.671
 */
2001:dd8:1c::/48 Deny No access allowed from Pakistan
2001:dec:8000::/48 Deny No access allowed from Pakistan
2001:df0:84::/48 Deny No access allowed from Pakistan
2001:df0:279::/48 Deny No access allowed from Pakistan
2001:df0:2cb::/48 Deny No access allowed from Pakistan
2001:df0:2c80::/48 Deny No access allowed from Pakistan
2001:df0:3200::/48 Deny No access allowed from Pakistan
2001:df0:5100::/48 Deny No access allowed from Pakistan
2001:df0:6c80::/48 Deny No access allowed from Pakistan
2001:df0:7880::/48 Deny No access allowed from Pakistan
2001:df0:7d80::/48 Deny No access allowed from Pakistan
2001:df0:8900::/48 Deny No access allowed from Pakistan
2001:df0:a480::/48 Deny No access allowed from Pakistan
2001:df0:c180::/48 Deny No access allowed from Pakistan
2001:df0:c900::/48 Deny No access allowed from Pakistan
2001:df1:4b00::/48 Deny No access allowed from Pakistan
2001:df1:5080::/48 Deny No access allowed from Pakistan
2001:df1:9100::/48 Deny No access allowed from Pakistan
2001:df1:a880::/48 Deny No access allowed from Pakistan
2001:df2:3080::/48 Deny No access allowed from Pakistan
2001:df2:8700::/48 Deny No access allowed from Pakistan
2001:df3:700::/48 Deny No access allowed from Pakistan
2001:df3:b200::/48 Deny No access allowed from Pakistan
2001:df4:4100::/48 Deny No access allowed from Pakistan
2001:df4:6200::/48 Deny No access allowed from Pakistan
2001:df4:7900::/48 Deny No access allowed from Pakistan
2001:df4:aa00::/48 Deny No access allowed from Pakistan
2001:df6:3c00::/48 Deny No access allowed from Pakistan
2001:df6:cd00::/48 Deny No access allowed from Pakistan
2001:df7:2500::/48 Deny No access allowed from Pakistan
2001:df7:a100::/48 Deny No access allowed from Pakistan
2001:fe8::/32 Deny No access allowed from Pakistan
2001:4538::/32 Deny No access allowed from Pakistan
2400:14c0::/32 Deny No access allowed from Pakistan
2400:1680::/32 Deny No access allowed from Pakistan
2400:1a80::/32 Deny No access allowed from Pakistan
2400:4f00::/32 Deny No access allowed from Pakistan
2400:8c40::/32 Deny No access allowed from Pakistan
2400:90c0::/32 Deny No access allowed from Pakistan
2400:9ac0::/32 Deny No access allowed from Pakistan
2400:9fc0::/32 Deny No access allowed from Pakistan
2400:a0c0::/32 Deny No access allowed from Pakistan
2400:ab40::/32 Deny No access allowed from Pakistan
2400:adc0::/27 Deny No access allowed from Pakistan
2400:b540::/32 Deny No access allowed from Pakistan
2400:b740::/32 Deny No access allowed from Pakistan
2400:b940::/32 Deny No access allowed from Pakistan
2400:bf40::/32 Deny No access allowed from Pakistan
2400:cb00:179::/48 Deny No access allowed from Pakistan
2400:cb00:186::/48 Deny No access allowed from Pakistan
2400:cb00:188::/48 Deny No access allowed from Pakistan
2400:cb00:207::/48 Deny No access allowed from Pakistan
2400:cb00:220::/48 Deny No access allowed from Pakistan
2400:d7c0::/32 Deny No access allowed from Pakistan
2400:fc00::/32 Deny No access allowed from Pakistan
2401::/31 Deny No access allowed from Pakistan
2401:1bc0::/32 Deny No access allowed from Pakistan
2401:2340::/32 Deny No access allowed from Pakistan
2401:30c0::/32 Deny No access allowed from Pakistan
2401:4100::/32 Deny No access allowed from Pakistan
2401:5540::/32 Deny No access allowed from Pakistan
2401:8e00::/32 Deny No access allowed from Pakistan
2401:9e00::/32 Deny No access allowed from Pakistan
2401:ba80::/32 Deny No access allowed from Pakistan
2401:e5c0::/32 Deny No access allowed from Pakistan
2401:ea00::/32 Deny No access allowed from Pakistan
2401:f840::/32 Deny No access allowed from Pakistan
2401:f8c0::/32 Deny No access allowed from Pakistan
2402:1040::/32 Deny No access allowed from Pakistan
2402:1680::/32 Deny No access allowed from Pakistan
2402:1c40::/32 Deny No access allowed from Pakistan
2402:2ec0::/32 Deny No access allowed from Pakistan
2402:3340::/32 Deny No access allowed from Pakistan
2402:7c00::/32 Deny No access allowed from Pakistan
2402:9640::/32 Deny No access allowed from Pakistan
2402:9e40::/32 Deny No access allowed from Pakistan
2402:9ec0::/32 Deny No access allowed from Pakistan
2402:a2c0::/32 Deny No access allowed from Pakistan
2402:ad80::/32 Deny No access allowed from Pakistan
2402:ba40::/32 Deny No access allowed from Pakistan
2402:e000::/32 Deny No access allowed from Pakistan
2402:ed40::/32 Deny No access allowed from Pakistan
2402:edc0::/32 Deny No access allowed from Pakistan
2402:f7c0::/32 Deny No access allowed from Pakistan
2402:fd00::/32 Deny No access allowed from Pakistan
2403:440::/32 Deny No access allowed from Pakistan
2403:dc0::/32 Deny No access allowed from Pakistan
2403:1bc0::/32 Deny No access allowed from Pakistan
2403:6340::/32 Deny No access allowed from Pakistan
2403:63c0::/32 Deny No access allowed from Pakistan
2403:7980::/32 Deny No access allowed from Pakistan
2403:7ec0::/32 Deny No access allowed from Pakistan
2403:a0c0::/32 Deny No access allowed from Pakistan
2403:a500::/32 Deny No access allowed from Pakistan
2403:bd40::/32 Deny No access allowed from Pakistan
2403:bec0::/32 Deny No access allowed from Pakistan
2403:c2c0::/32 Deny No access allowed from Pakistan
2403:d240::/32 Deny No access allowed from Pakistan
2403:ee40::/32 Deny No access allowed from Pakistan
2403:f5c0::/32 Deny No access allowed from Pakistan
2403:f7c0::/32 Deny No access allowed from Pakistan
2403:fcc0::/32 Deny No access allowed from Pakistan
2404:1940::/32 Deny No access allowed from Pakistan
2404:3100::/32 Deny No access allowed from Pakistan
2404:3c80::/32 Deny No access allowed from Pakistan
2404:5840::/32 Deny No access allowed from Pakistan
2404:6f40::/32 Deny No access allowed from Pakistan
2404:7000::/32 Deny No access allowed from Pakistan
2404:7680:1000::/36 Deny No access allowed from Pakistan
2404:7680:2000::/35 Deny No access allowed from Pakistan
2404:7680:4000::/34 Deny No access allowed from Pakistan
2404:7680:8000::/35 Deny No access allowed from Pakistan
2404:8300::/32 Deny No access allowed from Pakistan
2404:abc0::/32 Deny No access allowed from Pakistan
2404:c040::/32 Deny No access allowed from Pakistan
2404:d400::/32 Deny No access allowed from Pakistan
2404:e2c0::/32 Deny No access allowed from Pakistan
2404:ed80::/32 Deny No access allowed from Pakistan
2404:f0c0::/32 Deny No access allowed from Pakistan
2404:f400::/32 Deny No access allowed from Pakistan
2405:c00::/32 Deny No access allowed from Pakistan
2405:40c0::/32 Deny No access allowed from Pakistan
2406:d00::/32 Deny No access allowed from Pakistan
2406:1300::/32 Deny No access allowed from Pakistan
2406:7000::/32 Deny No access allowed from Pakistan
2406:8400::/32 Deny No access allowed from Pakistan
2406:ac00::/32 Deny No access allowed from Pakistan
2406:b280::/32 Deny No access allowed from Pakistan
2406:c380::/32 Deny No access allowed from Pakistan
2406:f480::/32 Deny No access allowed from Pakistan
2406:f500::/32 Deny No access allowed from Pakistan
2406:f580::/32 Deny No access allowed from Pakistan
2407:1280::/32 Deny No access allowed from Pakistan
2407:1b00::/32 Deny No access allowed from Pakistan
2407:3f80::/32 Deny No access allowed from Pakistan
2407:5b80::/32 Deny No access allowed from Pakistan
2407:8580::/32 Deny No access allowed from Pakistan
2407:9c00::/32 Deny No access allowed from Pakistan
2407:9e00::/32 Deny No access allowed from Pakistan
2407:aa80::/32 Deny No access allowed from Pakistan
2407:d000::/32 Deny No access allowed from Pakistan
2a01:ce9c::/36 Deny No access allowed from Pakistan
Origin: PK
