/**
 * Qatar netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Qatar
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: QA-2019.343.671
 */
5.1.45.0/24 Deny No access allowed from Qatar
5.62.61.92/30 Deny No access allowed from Qatar
5.62.63.68/30 Deny No access allowed from Qatar
5.101.222.128/25 Deny No access allowed from Qatar
5.175.151.128/25 Deny No access allowed from Qatar
5.180.36.0/22 Deny No access allowed from Qatar
31.11.48.0/22 Deny No access allowed from Qatar
31.11.52.0/24 Deny No access allowed from Qatar
31.11.53.128/25 Deny No access allowed from Qatar
31.11.54.0/23 Deny No access allowed from Qatar
37.186.32.0/19 Deny No access allowed from Qatar
37.208.128.0/17 Deny No access allowed from Qatar
37.210.0.0/15 Deny No access allowed from Qatar
45.11.74.0/24 Deny No access allowed from Qatar
45.12.70.188/32 Deny No access allowed from Qatar
45.12.71.188/32 Deny No access allowed from Qatar
46.243.147.0/24 Deny No access allowed from Qatar
57.88.192.0/20 Deny No access allowed from Qatar
66.96.126.64/26 Deny No access allowed from Qatar
77.81.92.0/24 Deny No access allowed from Qatar
77.81.94.0/24 Deny No access allowed from Qatar
78.100.0.0/15 Deny No access allowed from Qatar
80.76.160.0/22 Deny No access allowed from Qatar
80.76.164.0/23 Deny No access allowed from Qatar
80.76.166.64/27 Deny No access allowed from Qatar
80.76.166.99/32 Deny No access allowed from Qatar
80.76.166.102/32 Deny No access allowed from Qatar
80.76.166.224/28 Deny No access allowed from Qatar
80.76.167.192/26 Deny No access allowed from Qatar
80.76.168.0/21 Deny No access allowed from Qatar
81.29.160.0/20 Deny No access allowed from Qatar
82.148.96.0/19 Deny No access allowed from Qatar
86.36.0.0/15 Deny No access allowed from Qatar
86.62.192.0/18 Deny No access allowed from Qatar
89.211.0.0/16 Deny No access allowed from Qatar
94.125.224.0/21 Deny No access allowed from Qatar
104.166.112.0/24 Deny No access allowed from Qatar
128.90.62.0/24 Deny No access allowed from Qatar
140.82.203.0/24 Deny No access allowed from Qatar
154.84.170.0/24 Deny No access allowed from Qatar
157.167.92.0/24 Deny No access allowed from Qatar
162.158.8.0/23 Deny No access allowed from Qatar
162.158.10.0/24 Deny No access allowed from Qatar
165.124.236.0/22 Deny No access allowed from Qatar
176.202.0.0/15 Deny No access allowed from Qatar
178.23.16.0/21 Deny No access allowed from Qatar
178.152.0.0/15 Deny No access allowed from Qatar
179.61.192.0/26 Deny No access allowed from Qatar
179.61.192.64/27 Deny No access allowed from Qatar
179.61.192.96/30 Deny No access allowed from Qatar
179.61.192.100/31 Deny No access allowed from Qatar
179.61.192.104/29 Deny No access allowed from Qatar
179.61.192.112/28 Deny No access allowed from Qatar
179.61.192.128/25 Deny No access allowed from Qatar
181.215.140.80/28 Deny No access allowed from Qatar
185.2.244.0/22 Deny No access allowed from Qatar
185.25.12.0/22 Deny No access allowed from Qatar
185.37.96.0/22 Deny No access allowed from Qatar
185.37.108.0/22 Deny No access allowed from Qatar
185.62.164.0/24 Deny No access allowed from Qatar
185.96.224.0/22 Deny No access allowed from Qatar
185.100.208.0/22 Deny No access allowed from Qatar
185.104.56.0/22 Deny No access allowed from Qatar
185.107.76.0/22 Deny No access allowed from Qatar
185.139.237.0/27 Deny No access allowed from Qatar
185.139.237.32/28 Deny No access allowed from Qatar
185.139.237.48/30 Deny No access allowed from Qatar
185.139.237.52/31 Deny No access allowed from Qatar
185.139.237.55/32 Deny No access allowed from Qatar
185.139.237.56/29 Deny No access allowed from Qatar
185.139.237.64/27 Deny No access allowed from Qatar
185.139.237.96/28 Deny No access allowed from Qatar
185.139.237.112/30 Deny No access allowed from Qatar
185.139.237.116/31 Deny No access allowed from Qatar
185.139.237.119/32 Deny No access allowed from Qatar
185.139.237.120/29 Deny No access allowed from Qatar
185.154.168.0/22 Deny No access allowed from Qatar
185.239.92.0/22 Deny No access allowed from Qatar
185.247.88.0/22 Deny No access allowed from Qatar
194.6.255.0/24 Deny No access allowed from Qatar
194.50.99.188/32 Deny No access allowed from Qatar
194.50.111.188/32 Deny No access allowed from Qatar
198.44.137.72/29 Deny No access allowed from Qatar
198.44.139.80/29 Deny No access allowed from Qatar
198.44.149.232/29 Deny No access allowed from Qatar
199.127.102.0/25 Deny No access allowed from Qatar
204.97.87.136/32 Deny No access allowed from Qatar
212.70.96.0/19 Deny No access allowed from Qatar
212.77.192.0/19 Deny No access allowed from Qatar
213.130.96.0/20 Deny No access allowed from Qatar
213.130.112.0/22 Deny No access allowed from Qatar
213.130.118.0/23 Deny No access allowed from Qatar
213.130.120.0/21 Deny No access allowed from Qatar
213.178.136.0/22 Deny No access allowed from Qatar
213.206.136.212/32 Deny No access allowed from Qatar
Origin: QA
