/**
 * Qatar netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Qatar
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: QA-2019.343.671
 */
2001:1a10::/29 Deny No access allowed from Qatar
2400:cb00:54::/48 Deny No access allowed from Qatar
2620:0:876:6500::/56 Deny No access allowed from Qatar
2a00:7be0::/32 Deny No access allowed from Qatar
2a00:f0e0::/32 Deny No access allowed from Qatar
2a02:4440::/32 Deny No access allowed from Qatar
2a04:6f80::/30 Deny No access allowed from Qatar
2a04:7f80::/29 Deny No access allowed from Qatar
2a06:2f00::/29 Deny No access allowed from Qatar
2a06:4240::/29 Deny No access allowed from Qatar
2a09:3740::/29 Deny No access allowed from Qatar
2a0c:5180::/29 Deny No access allowed from Qatar
2a0c:a640::/29 Deny No access allowed from Qatar
2a0d:bc0::/29 Deny No access allowed from Qatar
2a0e:6702::/32 Deny No access allowed from Qatar
Origin: QA
