/**
 * Seychelles netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Seychelles
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: SC-2019.343.671
 */
2001:678:a18::/48 Deny No access allowed from Seychelles
2001:df1:5d80::/48 Deny No access allowed from Seychelles
2001:42e0::/32 Deny No access allowed from Seychelles
2001:43f8:a20::/47 Deny No access allowed from Seychelles
2400:fd40::/32 Deny No access allowed from Seychelles
2407:6780::/32 Deny No access allowed from Seychelles
2a03:42e0::/48 Deny No access allowed from Seychelles
2a04:1400::/29 Deny No access allowed from Seychelles
2a05:9f06::/31 Deny No access allowed from Seychelles
2a05:b300::/29 Deny No access allowed from Seychelles
2a06:e80::/29 Deny No access allowed from Seychelles
2a0c:4d00::/29 Deny No access allowed from Seychelles
2a0d:1a47:248::/48 Deny No access allowed from Seychelles
2a0d:2406:e1b::/48 Deny No access allowed from Seychelles
2c0f:efa0::/32 Deny No access allowed from Seychelles
2c0f:f0d0::/32 Deny No access allowed from Seychelles
2c0f:f248::/32 Deny No access allowed from Seychelles
2c0f:f360::/32 Deny No access allowed from Seychelles
2c0f:f530::/32 Deny No access allowed from Seychelles
2c0f:f680::/32 Deny No access allowed from Seychelles
2c0f:fd18::/32 Deny No access allowed from Seychelles
2c0f:fef0::/32 Deny No access allowed from Seychelles
Origin: SC
