/**
 * Syria netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Syria
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: SY-2019.343.671
 */
2a00:1ee8::/32 Deny No access allowed from Syria
2a00:45a0::/32 Deny No access allowed from Syria
2a00:70a0::/32 Deny No access allowed from Syria
2a00:b800::/29 Deny No access allowed from Syria
2a01:bd60::/32 Deny No access allowed from Syria
2a01:ce81::/32 Deny No access allowed from Syria
2a01:ce83:1000::/36 Deny No access allowed from Syria
2a01:ce83:2000::/35 Deny No access allowed from Syria
2a01:ce83:4000::/34 Deny No access allowed from Syria
2a01:ce83:8000::/35 Deny No access allowed from Syria
2a01:ce83:b000::/36 Deny No access allowed from Syria
2a01:ce83:c000::/34 Deny No access allowed from Syria
2a02:4520::/32 Deny No access allowed from Syria
2a02:67c0::/32 Deny No access allowed from Syria
2a03:8b60::/32 Deny No access allowed from Syria
2a04:8180::/31 Deny No access allowed from Syria
2a04:9080::/29 Deny No access allowed from Syria
2a05:a8c0::/29 Deny No access allowed from Syria
2a06:6f80::/29 Deny No access allowed from Syria
2a06:d300::/29 Deny No access allowed from Syria
2a07:4fc0::/29 Deny No access allowed from Syria
2a07:6980::/29 Deny No access allowed from Syria
2a09:b4c0::/29 Deny No access allowed from Syria
2a09:ebc0::/29 Deny No access allowed from Syria
2a0b:b6c0::/29 Deny No access allowed from Syria
2a0c:9940::/29 Deny No access allowed from Syria
2a0d:4100::/32 Deny No access allowed from Syria
2a0d:8b80::/29 Deny No access allowed from Syria
2a0d:e900::/29 Deny No access allowed from Syria
2a0f:b940::/32 Deny No access allowed from Syria
Origin: SY
