/**
 * Turkmenistan netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Turkmenistan
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: TM-2019.343.671
 */
2a02:7200::/32 Deny No access allowed from Turkmenistan
2a05:2180::/29 Deny No access allowed from Turkmenistan
Origin: TM
