/**
 * Turkmenistan netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Turkmenistan
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: TM-2019.343.671
 */
5.62.61.188/30 Deny No access allowed from Turkmenistan
5.62.63.168/30 Deny No access allowed from Turkmenistan
45.12.70.223/32 Deny No access allowed from Turkmenistan
45.12.71.223/32 Deny No access allowed from Turkmenistan
45.59.159.0/24 Deny No access allowed from Turkmenistan
46.36.201.116/30 Deny No access allowed from Turkmenistan
46.36.201.120/32 Deny No access allowed from Turkmenistan
94.102.184.0/24 Deny No access allowed from Turkmenistan
95.47.57.0/24 Deny No access allowed from Turkmenistan
95.85.96.0/19 Deny No access allowed from Turkmenistan
155.254.230.0/24 Deny No access allowed from Turkmenistan
178.171.66.0/23 Deny No access allowed from Turkmenistan
185.69.184.0/22 Deny No access allowed from Turkmenistan
185.246.72.0/22 Deny No access allowed from Turkmenistan
194.50.99.223/32 Deny No access allowed from Turkmenistan
194.50.111.223/32 Deny No access allowed from Turkmenistan
195.191.230.0/23 Deny No access allowed from Turkmenistan
206.123.152.128/25 Deny No access allowed from Turkmenistan
217.174.224.0/20 Deny No access allowed from Turkmenistan
Origin: TM
