/**
 * Uruguay netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Uruguay
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: UY-2019.343.671
 */
2001:1328::/32 Deny No access allowed from Uruguay
2001:1348::/32 Deny No access allowed from Uruguay
2001:13c7:7001::/48 Deny No access allowed from Uruguay
2001:13c7:7002::/47 Deny No access allowed from Uruguay
2001:13c7:7005::/48 Deny No access allowed from Uruguay
2001:13c7:7006::/47 Deny No access allowed from Uruguay
2001:13c7:7008::/47 Deny No access allowed from Uruguay
2001:13c7:7010::/46 Deny No access allowed from Uruguay
2001:13c7:7020::/44 Deny No access allowed from Uruguay
2800:a0::/28 Deny No access allowed from Uruguay
2800:250::/32 Deny No access allowed from Uruguay
2800:700::/32 Deny No access allowed from Uruguay
2800:840::/32 Deny No access allowed from Uruguay
2801::/48 Deny No access allowed from Uruguay
2801:0:2000::/36 Deny No access allowed from Uruguay
2801:14:a000::/47 Deny No access allowed from Uruguay
2801:1b:2000::/48 Deny No access allowed from Uruguay
2801:128::/36 Deny No access allowed from Uruguay
2801:1b8::/44 Deny No access allowed from Uruguay
2803:2680::/32 Deny No access allowed from Uruguay
2803:4e00::/32 Deny No access allowed from Uruguay
2803:8d80::/32 Deny No access allowed from Uruguay
2803:b200::/32 Deny No access allowed from Uruguay
2803:cfc0::/32 Deny No access allowed from Uruguay
2803:d600::/32 Deny No access allowed from Uruguay
2803:f120::/32 Deny No access allowed from Uruguay
2a01:ce90:b000::/36 Deny No access allowed from Uruguay
Origin: UY
