/**
 * Uruguay netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Uruguay
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: UY-2019.343.671
 */
5.62.56.245/32 Deny No access allowed from Uruguay
5.62.56.246/31 Deny No access allowed from Uruguay
5.62.58.225/32 Deny No access allowed from Uruguay
5.62.58.226/31 Deny No access allowed from Uruguay
37.35.105.218/31 Deny No access allowed from Uruguay
45.6.248.0/21 Deny No access allowed from Uruguay
45.12.70.235/32 Deny No access allowed from Uruguay
45.12.71.235/32 Deny No access allowed from Uruguay
45.94.161.0/24 Deny No access allowed from Uruguay
45.228.64.0/22 Deny No access allowed from Uruguay
57.75.80.20/30 Deny No access allowed from Uruguay
57.75.80.24/29 Deny No access allowed from Uruguay
57.75.80.32/27 Deny No access allowed from Uruguay
57.75.80.64/26 Deny No access allowed from Uruguay
57.75.80.128/25 Deny No access allowed from Uruguay
57.75.81.0/24 Deny No access allowed from Uruguay
57.75.82.0/23 Deny No access allowed from Uruguay
57.75.84.0/22 Deny No access allowed from Uruguay
57.75.88.0/21 Deny No access allowed from Uruguay
64.57.132.0/24 Deny No access allowed from Uruguay
92.118.186.0/25 Deny No access allowed from Uruguay
104.143.214.0/24 Deny No access allowed from Uruguay
128.90.119.0/24 Deny No access allowed from Uruguay
131.0.212.0/22 Deny No access allowed from Uruguay
138.59.12.0/22 Deny No access allowed from Uruguay
138.99.44.0/22 Deny No access allowed from Uruguay
152.156.0.0/16 Deny No access allowed from Uruguay
157.167.24.0/24 Deny No access allowed from Uruguay
159.180.12.0/24 Deny No access allowed from Uruguay
160.181.232.0/24 Deny No access allowed from Uruguay
161.0.120.0/21 Deny No access allowed from Uruguay
161.69.122.22/32 Deny No access allowed from Uruguay
163.198.104.0/24 Deny No access allowed from Uruguay
164.73.0.0/16 Deny No access allowed from Uruguay
167.56.0.0/13 Deny No access allowed from Uruguay
167.108.0.0/16 Deny No access allowed from Uruguay
167.116.0.0/16 Deny No access allowed from Uruguay
168.121.184.0/22 Deny No access allowed from Uruguay
170.51.56.0/22 Deny No access allowed from Uruguay
170.51.64.0/21 Deny No access allowed from Uruguay
170.51.192.0/21 Deny No access allowed from Uruguay
170.247.168.0/22 Deny No access allowed from Uruguay
178.170.140.0/24 Deny No access allowed from Uruguay
179.0.156.0/22 Deny No access allowed from Uruguay
179.24.0.0/13 Deny No access allowed from Uruguay
181.215.141.96/28 Deny No access allowed from Uruguay
185.125.225.28/32 Deny No access allowed from Uruguay
186.8.0.0/16 Deny No access allowed from Uruguay
186.48.0.0/13 Deny No access allowed from Uruguay
190.0.128.0/19 Deny No access allowed from Uruguay
190.14.12.0/24 Deny No access allowed from Uruguay
190.64.0.0/21 Deny No access allowed from Uruguay
190.64.16.0/20 Deny No access allowed from Uruguay
190.64.32.0/19 Deny No access allowed from Uruguay
190.64.64.0/18 Deny No access allowed from Uruguay
190.64.128.0/17 Deny No access allowed from Uruguay
190.99.96.0/20 Deny No access allowed from Uruguay
190.108.0.0/19 Deny No access allowed from Uruguay
190.112.52.0/22 Deny No access allowed from Uruguay
190.112.202.0/24 Deny No access allowed from Uruguay
190.114.3.128/25 Deny No access allowed from Uruguay
190.132.0.0/14 Deny No access allowed from Uruguay
191.101.201.0/24 Deny No access allowed from Uruguay
192.146.237.0/24 Deny No access allowed from Uruguay
194.50.99.235/32 Deny No access allowed from Uruguay
194.50.111.235/32 Deny No access allowed from Uruguay
195.112.185.249/32 Deny No access allowed from Uruguay
195.112.189.132/30 Deny No access allowed from Uruguay
198.50.104.232/29 Deny No access allowed from Uruguay
198.50.118.80/29 Deny No access allowed from Uruguay
198.50.121.208/29 Deny No access allowed from Uruguay
198.101.141.152/29 Deny No access allowed from Uruguay
200.0.68.0/23 Deny No access allowed from Uruguay
200.0.86.0/23 Deny No access allowed from Uruguay
200.0.88.0/24 Deny No access allowed from Uruguay
200.0.204.0/22 Deny No access allowed from Uruguay
200.2.32.0/19 Deny No access allowed from Uruguay
200.3.12.0/22 Deny No access allowed from Uruguay
200.7.84.0/22 Deny No access allowed from Uruguay
200.10.60.0/22 Deny No access allowed from Uruguay
200.12.155.0/24 Deny No access allowed from Uruguay
200.12.156.0/24 Deny No access allowed from Uruguay
200.32.125.80/29 Deny No access allowed from Uruguay
200.32.125.120/29 Deny No access allowed from Uruguay
200.35.153.0/24 Deny No access allowed from Uruguay
200.40.0.0/16 Deny No access allowed from Uruguay
200.58.128.0/19 Deny No access allowed from Uruguay
200.61.144.0/24 Deny No access allowed from Uruguay
200.71.0.0/19 Deny No access allowed from Uruguay
200.80.48.0/23 Deny No access allowed from Uruguay
200.80.50.0/24 Deny No access allowed from Uruguay
200.93.240.0/21 Deny No access allowed from Uruguay
200.108.192.0/18 Deny No access allowed from Uruguay
200.115.72.0/21 Deny No access allowed from Uruguay
200.124.192.0/21 Deny No access allowed from Uruguay
200.124.200.0/22 Deny No access allowed from Uruguay
200.124.204.0/23 Deny No access allowed from Uruguay
200.124.207.0/24 Deny No access allowed from Uruguay
200.124.208.0/20 Deny No access allowed from Uruguay
200.125.0.0/18 Deny No access allowed from Uruguay
201.217.128.0/18 Deny No access allowed from Uruguay
201.219.224.0/21 Deny No access allowed from Uruguay
201.219.252.0/22 Deny No access allowed from Uruguay
201.221.0.0/18 Deny No access allowed from Uruguay
212.63.189.52/30 Deny No access allowed from Uruguay
Origin: UY
