/**
 * Uzbekistan netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Uzbekistan
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: UZ-2019.343.671
 */
2001:678:860::/48 Deny No access allowed from Uzbekistan
2a00:8840::/29 Deny No access allowed from Uzbekistan
2a01:ce8d:1000::/36 Deny No access allowed from Uzbekistan
2a01:ce8d:2000::/35 Deny No access allowed from Uzbekistan
2a01:ce8d:4000::/34 Deny No access allowed from Uzbekistan
2a01:ce8d:8000::/35 Deny No access allowed from Uzbekistan
2a01:ce8d:b000::/36 Deny No access allowed from Uzbekistan
2a01:ce8d:c000::/34 Deny No access allowed from Uzbekistan
2a02:a98::/32 Deny No access allowed from Uzbekistan
2a02:f10::/32 Deny No access allowed from Uzbekistan
2a02:c8c0::/29 Deny No access allowed from Uzbekistan
2a02:f7c0::/29 Deny No access allowed from Uzbekistan
2a03:540::/32 Deny No access allowed from Uzbekistan
2a03:1020::/32 Deny No access allowed from Uzbekistan
2a03:3240::/32 Deny No access allowed from Uzbekistan
2a03:46e0::/32 Deny No access allowed from Uzbekistan
2a03:8ee0::/32 Deny No access allowed from Uzbekistan
2a04:1b80::/32 Deny No access allowed from Uzbekistan
2a05:45c0::/29 Deny No access allowed from Uzbekistan
2a07:edc0::/29 Deny No access allowed from Uzbekistan
2a09:5c00::/29 Deny No access allowed from Uzbekistan
2a09:6700::/29 Deny No access allowed from Uzbekistan
2a09:adc0::/29 Deny No access allowed from Uzbekistan
2a09:c040::/29 Deny No access allowed from Uzbekistan
2a09:f380::/29 Deny No access allowed from Uzbekistan
2a0b:1c80::/29 Deny No access allowed from Uzbekistan
2a0b:9540::/29 Deny No access allowed from Uzbekistan
2a0c:5d80::/29 Deny No access allowed from Uzbekistan
2a0e:17c0::/29 Deny No access allowed from Uzbekistan
2a0e:9f00::/29 Deny No access allowed from Uzbekistan
2a0f:7f40::/29 Deny No access allowed from Uzbekistan
Origin: UZ
