/**
 * Uzbekistan netblocks.
 *
 * This file is an optional blocklist for the CIDRAM package.
 * It will block access from Uzbekistan
 *
 * This file includes GeoLite data created by MaxMind, available from https://dev.maxmind.com/geoip/geoip2/geolite2/
 * The GeoLite databases are distributed under the Creative Commons Attribution-ShareAlike 4.0 International License
 * http://creativecommons.org/licenses/by-sa/4.0/
 *
 * Aggregated and adapted to work with CIDRAM by David MacMathan (macmathan).
 * https://bitbucket.org/macmathan
 *
 * Last updated 2019.12.10 1607
 *
 * Version: UZ-2019.343.671
 */
2.57.60.0/22 Deny No access allowed from Uzbekistan
5.62.61.204/30 Deny No access allowed from Uzbekistan
5.62.63.192/30 Deny No access allowed from Uzbekistan
5.101.217.0/25 Deny No access allowed from Uzbekistan
5.182.26.0/24 Deny No access allowed from Uzbekistan
5.188.132.0/24 Deny No access allowed from Uzbekistan
31.40.24.0/21 Deny No access allowed from Uzbekistan
31.135.208.0/21 Deny No access allowed from Uzbekistan
31.148.144.0/22 Deny No access allowed from Uzbekistan
31.148.208.0/22 Deny No access allowed from Uzbekistan
31.148.220.0/24 Deny No access allowed from Uzbekistan
34.99.198.0/23 Deny No access allowed from Uzbekistan
34.103.142.0/23 Deny No access allowed from Uzbekistan
34.103.214.0/23 Deny No access allowed from Uzbekistan
37.110.208.0/21 Deny No access allowed from Uzbekistan
45.9.228.0/22 Deny No access allowed from Uzbekistan
45.12.70.236/32 Deny No access allowed from Uzbekistan
45.12.71.236/32 Deny No access allowed from Uzbekistan
45.59.153.0/24 Deny No access allowed from Uzbekistan
45.91.220.0/22 Deny No access allowed from Uzbekistan
46.8.35.0/24 Deny No access allowed from Uzbekistan
46.227.120.0/21 Deny No access allowed from Uzbekistan
46.255.64.0/21 Deny No access allowed from Uzbekistan
57.93.64.0/20 Deny No access allowed from Uzbekistan
62.209.128.0/19 Deny No access allowed from Uzbekistan
80.80.208.0/20 Deny No access allowed from Uzbekistan
81.95.224.0/20 Deny No access allowed from Uzbekistan
82.215.64.0/18 Deny No access allowed from Uzbekistan
83.69.128.0/19 Deny No access allowed from Uzbekistan
83.221.160.0/19 Deny No access allowed from Uzbekistan
84.54.64.0/18 Deny No access allowed from Uzbekistan
86.62.0.0/22 Deny No access allowed from Uzbekistan
87.237.232.0/21 Deny No access allowed from Uzbekistan
89.146.64.0/19 Deny No access allowed from Uzbekistan
89.146.96.0/24 Deny No access allowed from Uzbekistan
89.146.98.0/23 Deny No access allowed from Uzbekistan
89.146.100.0/22 Deny No access allowed from Uzbekistan
89.146.104.0/21 Deny No access allowed from Uzbekistan
89.146.112.0/20 Deny No access allowed from Uzbekistan
89.236.192.0/18 Deny No access allowed from Uzbekistan
91.90.216.0/22 Deny No access allowed from Uzbekistan
91.188.128.0/19 Deny No access allowed from Uzbekistan
91.196.76.0/22 Deny No access allowed from Uzbekistan
91.203.172.0/22 Deny No access allowed from Uzbekistan
91.204.236.0/22 Deny No access allowed from Uzbekistan
91.212.89.0/24 Deny No access allowed from Uzbekistan
91.212.124.0/24 Deny No access allowed from Uzbekistan
91.212.180.0/24 Deny No access allowed from Uzbekistan
91.213.31.0/24 Deny No access allowed from Uzbekistan
91.213.248.0/24 Deny No access allowed from Uzbekistan
91.227.14.0/23 Deny No access allowed from Uzbekistan
91.229.160.0/22 Deny No access allowed from Uzbekistan
91.229.164.0/23 Deny No access allowed from Uzbekistan
91.231.56.0/22 Deny No access allowed from Uzbekistan
91.234.218.0/23 Deny No access allowed from Uzbekistan
91.240.12.0/22 Deny No access allowed from Uzbekistan
92.38.24.0/22 Deny No access allowed from Uzbekistan
92.38.52.0/22 Deny No access allowed from Uzbekistan
92.119.248.0/22 Deny No access allowed from Uzbekistan
92.223.37.0/24 Deny No access allowed from Uzbekistan
92.253.192.0/21 Deny No access allowed from Uzbekistan
93.157.58.0/24 Deny No access allowed from Uzbekistan
93.170.160.0/22 Deny No access allowed from Uzbekistan
93.170.208.0/22 Deny No access allowed from Uzbekistan
93.171.72.0/22 Deny No access allowed from Uzbekistan
93.171.148.0/22 Deny No access allowed from Uzbekistan
93.171.188.0/22 Deny No access allowed from Uzbekistan
93.171.228.0/23 Deny No access allowed from Uzbekistan
94.141.64.0/19 Deny No access allowed from Uzbekistan
94.158.48.0/20 Deny No access allowed from Uzbekistan
94.230.224.0/20 Deny No access allowed from Uzbekistan
94.232.24.0/22 Deny No access allowed from Uzbekistan
95.46.64.0/21 Deny No access allowed from Uzbekistan
95.46.90.0/24 Deny No access allowed from Uzbekistan
95.46.92.0/24 Deny No access allowed from Uzbekistan
95.46.100.0/22 Deny No access allowed from Uzbekistan
95.214.208.0/22 Deny No access allowed from Uzbekistan
109.207.240.0/20 Deny No access allowed from Uzbekistan
109.248.220.0/23 Deny No access allowed from Uzbekistan
139.28.44.0/22 Deny No access allowed from Uzbekistan
146.120.16.0/22 Deny No access allowed from Uzbekistan
146.120.192.0/22 Deny No access allowed from Uzbekistan
146.158.16.0/21 Deny No access allowed from Uzbekistan
155.254.197.0/24 Deny No access allowed from Uzbekistan
178.171.38.0/24 Deny No access allowed from Uzbekistan
178.216.128.0/21 Deny No access allowed from Uzbekistan
178.218.200.0/21 Deny No access allowed from Uzbekistan
185.4.160.0/22 Deny No access allowed from Uzbekistan
185.6.40.0/22 Deny No access allowed from Uzbekistan
185.8.212.0/22 Deny No access allowed from Uzbekistan
185.63.224.0/22 Deny No access allowed from Uzbekistan
185.74.4.0/22 Deny No access allowed from Uzbekistan
185.74.100.0/22 Deny No access allowed from Uzbekistan
185.78.136.0/22 Deny No access allowed from Uzbekistan
185.93.124.0/22 Deny No access allowed from Uzbekistan
185.139.136.0/22 Deny No access allowed from Uzbekistan
185.163.24.0/22 Deny No access allowed from Uzbekistan
185.183.240.0/22 Deny No access allowed from Uzbekistan
185.196.212.0/22 Deny No access allowed from Uzbekistan
185.196.216.0/22 Deny No access allowed from Uzbekistan
185.208.176.0/22 Deny No access allowed from Uzbekistan
185.211.128.0/22 Deny No access allowed from Uzbekistan
185.230.204.0/22 Deny No access allowed from Uzbekistan
185.239.152.0/22 Deny No access allowed from Uzbekistan
185.248.44.0/22 Deny No access allowed from Uzbekistan
188.113.192.0/18 Deny No access allowed from Uzbekistan
188.130.162.0/24 Deny No access allowed from Uzbekistan
192.166.228.0/22 Deny No access allowed from Uzbekistan
193.27.206.0/23 Deny No access allowed from Uzbekistan
193.107.16.0/24 Deny No access allowed from Uzbekistan
193.107.17.71/32 Deny No access allowed from Uzbekistan
193.107.17.150/32 Deny No access allowed from Uzbekistan
193.107.18.0/23 Deny No access allowed from Uzbekistan
194.32.96.0/22 Deny No access allowed from Uzbekistan
194.50.99.236/32 Deny No access allowed from Uzbekistan
194.50.111.236/32 Deny No access allowed from Uzbekistan
194.55.92.0/22 Deny No access allowed from Uzbekistan
195.7.15.0/24 Deny No access allowed from Uzbekistan
195.69.188.0/22 Deny No access allowed from Uzbekistan
195.88.214.0/23 Deny No access allowed from Uzbekistan
195.158.0.0/19 Deny No access allowed from Uzbekistan
195.211.180.0/22 Deny No access allowed from Uzbekistan
206.123.150.128/25 Deny No access allowed from Uzbekistan
209.206.29.240/28 Deny No access allowed from Uzbekistan
212.115.112.0/22 Deny No access allowed from Uzbekistan
213.206.32.0/19 Deny No access allowed from Uzbekistan
213.230.64.0/18 Deny No access allowed from Uzbekistan
217.12.80.0/20 Deny No access allowed from Uzbekistan
217.29.112.0/20 Deny No access allowed from Uzbekistan
217.30.160.0/20 Deny No access allowed from Uzbekistan
Origin: UZ
